TACC/Core-CMS-Custom

- apcd-cms/src/taccsite_cms/custom_app_settings.py
When the image is built, static files live under `/code/taccsite_custom`.
> Use taccsite_custom dir for static files.

- apcd-cms/Dockerfile
- apcd-cms/src/taccsite_cms/settings_custom.py
Updates from Core-CMS: new variable, new template.
- [FP-1801]
- requires https://github.com/TACC/Core-CMS/pull/549
- mirrors APCD change in https://github.com/TACC/Core-CMS-Resources/pull/164
- feat(apcd): FP-1802 use tam getting started guide
0. Log in to CMS https://txapcd.org/admin.
1. (if not already present) Add a redirect from `/tam/register` to https://accounts-dev.tacc.utexas.edu/apcd/register .[^1]
[^1]: To avoid this requirement per Portal that uses TAM, we could instead add redirects in `urls.py` in CMS [or in Portal](https://github.com/TACC/Core-Portal/pull/688#discussion_r956488404).
0. Log in to CMS https://txapcd.org/admin.
1. Open https://txapcd.org/help/getting-started/.
2. Confirm that the content beneath header matches this screenshot:
3. Verify it uses template …
> Task/fp 1801 guides […] - getting started via tam

- apcd-cms/src/taccsite_cms/settings_custom.py
Do not add default e-mail settings.
- [FP-1823](https://jira.tacc.utexas.edu/browse/FP-1823)
- requires https://github.com/TACC/Core-CMS/pull/550
- mirrored by https://github.com/TACC/Core-CMS-Resources/pull/165
- remove hard-coded remote e-mail host
- add comment to direct developer to instructions
See https://github.com/TACC/Core-CMS/pull/550.
> fix(settings): fp-1823 do not define email settings

- apcd-cms/Dockerfile
Update APCD CMS Dockerfile tag to use https://github.com/TACC/Core-CMS/pull/551.
- [FP-1808](https://jira.tacc.utexas.edu/browse/FP-1808)
- relies on https://github.com/TACC/Core-CMS/pull/551
- change APCD CMS Dockerfile tag
See https://github.com/TACC/Core-CMS/pull/551.
> feat(apcd-cms): fp-1808 cms docker tag

- README.md
- apcd-cms/README.md
Migrate apcd-cms `Readme.md` to root, because most of its content is applicable to any custom CMS.
- none
- migrate `apcd-cms/README.md` to root
- add minimal `apcd-cms/README.md`
1. Read root readme via https://github.com/TACC/Core-CMS-Custom/tree/task/move-readme-to-root.
2. Read apcd-cms readme via https://github.com/TACC/Core-CMS-Custom/tree/task/move-readme-to-root/apcd-cms.
3. Report problems or concerns.
> docs: migrate readme to root

- apcd-cms/src/apps/submission_form/templates/submission_form/submission_form.html
Tweak help text for "Types of Files".\
<sub>Duplicates, but isolates, 3082d09 from #16.</sub>
- [a design/dev agreement](https://tacc-team.slack.com/archives/C03B7899YD8/p1666110193691849?thread_ts=1666104477.412489&cid=C03B7899YD8)
0. Change code in [`apcd-cms/src/apps/submission_form/views.py#L13-L21`](https://github.com/TACC/Core-CMS-Custom/blob/75ec406/apcd-cms/src/apps/submission_form/views.py#L13-L21) to set template and return response first.
<details>
From:
```python
def get(self, request):
template = loader.get_template('submission_form/submission_form.html')
return HttpResponse(template.render({}, request))
user = authenticate(request)
if user:
template = loader.get_template('submission_form/submission_form.html')
return HttpResponse(template.render({}, request))
else:
return …
```
> feat(apcd-cms): tweak "Types of Files" help text

- apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/registrations_table.css
- apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
Responsive tables for Registration list.
- [FP-1818](https://jira.tacc.utexas.edu/browse/FP-1818)
- builds upon https://github.com/TACC/Core-CMS-Custom/pull/29
- allow table to stretch and shrink
- use variable for cell padding
- move row background from cells to rows
- use line-height (not padding) for space between list items
- add responsive table styles
- add empty space and comment for missing action/s
1. Follow "Testing" of https://github.com/TACC/Core-CMS-Custom/pull/29.
2. View table at different screen widths.
3. Verify table content is legible, accessible, aesthetic, et cetera.
[Designer review is in Slack.](https://tacc-team.slack.com/archives/CTBCB8ZD0/p1666721928626939)
| < 768px | > 768px | 1680px |
| - | - | - |
| ![768px](https://user-images.githubusercontent.com/62723358/1 …
> fix(apcd-cms): fp-1818 responsive table UI

- apcd-cms/Dockerfile
- apcd-cms/src/apps/registrations/views.py
Fixed error template returned for submission errors.
- [FP-1907](https://jira.tacc.utexas.edu/browse/FP-1907)
Replace error placeholder text with actual error template to be rendered upon receiving an error message.
(locally)
1. If you do not have the RT secrets you'll need to grab them from stache and put them in you local secrets file. Otherwise, you will need to go to `apcd-cms/src/apps/registrations/views.py` comment out the lines in the `post` method related to the RT `tracker`
2. Submit a completed form with jibberish (It will fail and you should see the failure screen)
> Task/FP-1907 - Template path error

- apcd-cms/Dockerfile
<details><summary>To Do</summary>
1. [x] deploy → [job #2098](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/2098)
2. [x] test on APCD QA server
3. [x] take screenshots
4. [x] request reviewers
</details>
Load button width fix from Core-CMS.
- [FP-1791](https://jira.tacc.utexas.edu/browse/FP-1791)
- requires https://github.com/TACC/Core-CMS/pull/560
See https://github.com/TACC/Core-CMS/pull/560.
> fix(apcd): fp-1791 button width too narrow

- apcd-cms/Dockerfile
- apcd-cms/src/apps/registrations/templates/submission_form/submission_form.html
Fix dollar sign position (via https://github.com/TACC/Core-CMS/pull/567).
Fix missing CSS (migrated to Core in #42).
- [FP-1823](https://jira.tacc.utexas.edu/browse/FP-1828)
- requires https://github.com/TACC/Core-Styles/pull/62
available via https://github.com/TACC/Core-CMS/pull/567
- add class for firefox
- load new cms image
0. Use Firefox browser.
1. Open http://localhost:8000/register/request-to-submit/.
2. Verify "Total Claims Value" dollar sign is within input (not outside it).
3. Verify fields have a max-width again.
4. (optional) Verify other FP-1828 styles have been restored.
<sub>Build: https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/853/</sub>
<sub>Deploy: https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/2159</sub>
| Before | After |
| - | - |
| <img width="1104" …
> fix(apcd-cms): dollar sign position & core styles v0.10.0

- apcd-cms/src/apps/admin_regis_table/templates/create_submitter_modal.html
- apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
- apcd-cms/src/apps/utils/apcd_database.py
Addressed incorrect filter value and non-functional create submitter modal
…
- [FP-1819](https://jira.tacc.utexas.edu/browse/FP-1819)
- [FP-1938](https://jira.tacc.utexas.edu/browse/FP-1938)
…
- Changed filter value from 'Completed' to 'Complete' (to match database)
- Changed input type for payor + submitter codes (had mixed up) and marked all fields in create submitter modal form as required
- Fixed incorrect keys used for indexing create submitter form data in database writing function
…
1. **Testing database reading/writing locally will not work, so expect to get an error when trying to submit create submitter form**
2. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
(
1, …
> hotfix: Create submitter modal and list registrations filtering

- apcd-cms/src/apps/admin_regis_table/templates/create_submitter_modal.html
- apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
- apcd-cms/src/apps/utils/apcd_database.py
…
- [FP-1819](https://jira.tacc.utexas.edu/browse/FP-1819)
…
Changed value for `payor_code` to now process as an int
…
1. **Testing database reading/writing locally will not work, so expect to get an error when trying to submit create submitter form**
2. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
(
False,                               #file_pv
True,                               #file_mc
True, …
> hotfix: Create submitter modal - swapped payor and submitter codes

- apcd-cms/src/apps/admin_regis_table/templates/create_submitter_modal.html
- apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
- apcd-cms/src/apps/admin_regis_table/views.py
- apcd-cms/src/apps/utils/apcd_database.py
Converted links to action modals in 'Actions' column on admin registrations listing to a dropdown
…
- [FP-1963](https://jira.tacc.utexas.edu/browse/FP-1963)
…
- Removed links from actions column
- Added `select` element containing options corresponding to each action
- Added JSX function to open modal upon clicking in `select`
- Removed old code from table view 
…
1. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
( …
> task/FP-1963: Move actions to dropdown

- apcd-cms/src/apps/admin_submissions/views.py
Fixed navigation to `/administration/list-submissions` if the `page` parameter is missing
- [FP-1924](https://jira.tacc.utexas.edu/browse/FP-1924)
1. Added a catch for missing `page` parameter
1. Follow same setup procedure as highlighted in the [previous PR](https://github.com/TACC/Core-CMS-Custom/pull/68)
2. Navigate to [http://localhost:8000/administration/list-submissions/](http://localhost:8000/administration/list-submissions/) and ensure page loads and navigates to the first page
> Admin Submissions Navigation Fix

- apcd-cms/src/apps/admin_regis_table/views.py
Added `NoneType` handling for organization type from APCD database for listing registrations page
…
…
- Added catch for value `None` when handling organization type in listing table & modals
…
1. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
(
False,                               #file_pv
True,                               #file_mc
True,                               #file_pc
False, …
> Handling for a few NoneType values in database in registrations listing

- apcd-cms/src/apps/utils/apcd_database.py
Fixes for edit registration and create submitter actions on list registration requests admin page
…
…
- Added a missing value field for create submitter SQL operation command
- Added missing `cur` definition in update registration util function
- Reformatted current time call for update registration operation
…
1. Will have to test on QA server, I've tested the revised util functions separately and they work.
2. Therefore, nothing to test locally.
…
> hotfix: Create submitter and edit registration not writing to database

- apcd-cms/src/apps/admin_regis_table/templates/edit_registration_error.html
- apcd-cms/src/apps/utils/apcd_database.py
…
…
- Wrapped some args in `' '` to pick up entire input string from form
- Added error message styling to edit registration error page to show error message correctly
…
1. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
(
False,                               #file_pv
True,                               #file_mc
True,                               #file_pc
False,                              #file_dc
True, …
> hotfix: Edit registration args needing string-wrap to read correctly

- apcd-cms/src/apps/admin_regis_table/views.py
Hotfix to make `admin_regis_table` load the new data on render
Added `get...` calls to the `dispatch()` function
…
Can't test locally, will need to add to PPRD. 
1.  Navigate to https://apcd-qa.tacc.utexas.edu/administration/list-registration-requests/
2. Edit an entry.
3. Navigate through workflow
4. Make sure changes are visible when you lang back at the `list-registration-requests/` table
…
> Added functions to get registration data on page render

- apcd-cms/src/apps/extension/views.py
- apcd-cms/src/apps/utils/apcd_database.py
Update to allow extension form to make extension entries to DB for more than one extension per form using the add extension button
- [FP-1816](https://jira.tacc.utexas.edu/browse/FP-1816)
Created a while loop and iterator to go through each extension field in form and insert
1. Go to [http://localhost:8000/submissions/extension-request/](http://localhost:8000/submissions/extension-request/)
2. Use snippet below and put in extension/views.py on line 24 
```
submitters = [
(2, 'TESTGOLD', 10000001, 'gmunoz1', 'CHCD'),
(3, 'TESTGOLD', 10000002, 'gmunoz1', 'CHCD'),
(1, 'TESTGOLD', 10000000, 'gmunoz1', 'CHCD')
]
```
3. Nothing to test locally - just make sure the extension form looks the same and doesn't display error template on submit.
…
> Fix extension to store more than one extension request

- apcd-cms/src/apps/utils/apcd_database.py
Needed to change how `WHERE` clause in `get_registrations` & related util functions is included/excluded in SQL command
…
…
- Reverted to f-string solution to completely exclude `WHERE` from SQL command if `reg_id` is not passed
…
1. Nothing to test locally.
…
> fix: Bad default arg for reg id util functions

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
- apcd-cms/src/apps/utils/apcd_database.py
Added frontend pattern checks to prevent malformed email submissions that don't get saved to the db because they don't match our data sanitizers
* [CEPWMA-687](https://jira.tacc.utexas.edu/browse/CEPWMA-687)
Adds front-end check that prevents users from submitting malformed emails.
1. Go to [Request to Submit](http://localhost:8000/register/request-to-submit/) page and try to add a contact with a malformed email, and make sure you are prevented from doing so.
2. Try to submit a correctly formatted email, and make sure that you are able to.
> CEPWMA-687 - hotfix/email-validation

- apcd-cms/src/apps/utils/apcd_database.py
Added fix for eligibility/enrollment file type not writing to db unless other file types selected
…
…
- In `create_registration` db function, I set `file_me` to always be set as `True` as this file type is mandatory for all registration requests
…
1. No testing to do locally.
…
> fix: Eligibility/enrollment file type not storing correctly to database

- apcd-cms/src/apps/admin_regis_table/views.py
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
- apcd-cms/src/apps/utils/apcd_database.py
Addressed a few bugs that made writing registration entities and contacts work inconsistently
…
…
- Swapped `iteration` number and `reg_id` in relevant util db functions to match templates
- Set default `None` value for entity identifiers (at least one of three required at time of registration)
- In template scripts, added entity number to fix how entity blocks were being grabbed by input listener script
- In template body, added conditionality to `value` parameter for entity identifiers for edit modal (see above)
…
1. Replace lines 67-69 in `apps/admin_regis_table/views.py` with the following:
(
12023, …
> fix: Registration listing - entities and contacts not writing correctly to database

- apcd-cms/src/apps/utils/apcd_database.py
Create registration contact call coming from update registration contact function missing parameter
…
…
- Added `True` for `from_update_reg` parameter in call for function `create_registration_contact` coming from `update_registration_contact`
…
1. No testing needed! 
…
> fix: Added missing parameter to create_registration_contact call

- apcd-cms/src/apps/view_users/templates/view_users.html
…Had a sort script to alphabetize dropdown which became redundant after SQL query fixed. Script also made list look wonky
…
Removed unneeded script
…
1. Tested using fake data
2. user_content = [
(
6,
4,
'aw@heck.org',
'Jon Heck',
'UHC',
'no create',
'none update',
'no notes',
't',
'submitter'
),
(
5,
4,
'aw@heck.org',
'Jon Heck',
't',
'no create',
'none update',
'no notes',
't',
'submitter'
),
(
5,
4,
'aw@heck.org',
'Jon Heck',
'UHC',
'no create',
'none update',
'no notes',
't',
'submitter'
),           
]
…Looks the same
> remove sort script to fix broken list

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
Fix data submission guide link on exception page. The APCD homepage link worked correctly
- [FP-2002](https://jira.tacc.utexas.edu/browse/FP-2002)
Fixed link to go to the same page as in the Get Help page for the data submission guide.
1. Put snippet on line 33 and 97 for exceptions/views.py <summary>Snippet <details>[ (2, 'TESTGOLD', 10000001, 'gmunoz1', 'CHCD'), (3, 'TESTGOLD', 10000002, 'gmunoz1', 'CHCD'), (1, 'TESTGOLD', 10000000, 'gmunoz1', 'CHCD') ]</details><summary>
2. Go to [http://localhost:8000/submissions/other-exception/](http://localhost:8000/submissions/other-exception/ ) and[http://localhost:8000/submissions/threshold-exception/](http://localhost:8000/submissions/threshold-exception/)
4. Make sure all links work on the threshold and other exception pages
5. Using snippet …
> Fixed link for data-submission page. APCD home was working correctly

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_other_form.html
- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
UTHealth gave notes that subscripts were numbered 3, 4, 5 versus 1, 2, 3. Also, have extra notes at bottom of screen listed as 1 and 2 that need to be removed if not in use.
- [FP-2005](https://jira.tacc.utexas.edu/browse/FP-2005)
For subscripts:
- Changed numbering 
- Removed unused subscripts
- Renumbered
1. Put snippet on line 33 and 97 for exceptions/views.py <summary>Snippet <details>[ (2, 'TESTGOLD', 10000001, 'gmunoz1', 'CHCD'), (3, 'TESTGOLD', 10000002, 'gmunoz1', 'CHCD'), (1, 'TESTGOLD', 10000000, 'gmunoz1', 'CHCD') ]</details><summary>
2. Go to [http://localhost:8000/submissions/other-exception/](http://localhost:8000/submissions/other-exception/ ) and [http://localhost:8000/submissions/threshold-exception/](http://localhost:8000/submissions/threshold-exception/)
4. Make sure …
> bug/FP-2005 Exception/Extension Forms - cited text numbering - UTH

- apcd-cms/src/apps/view_users/views.py
Addition of 'user-number' to table led to column mismatch. in consultation with Carrie have created a fix to have table show role_names again
…
Changed  column number assigned to role_names from (9) to (10) as user_number was inserted before it.
…
1. Can only test against database 
…
> changed column number to reflect change in table and show rolenames

- apcd-cms/src/apps/registrations/static/registrations/css/submission_form.css
…
- [FP-1977](https://jira.tacc.utexas.edu/browse/FP-1977)
…
- Added CSS for `input` to hide scroll arrows from browser
…
1. Navigate to http://localhost:8000/register/request-to-submit/
2. Fill out all required fields prior to entity 'coverage estimates'
3. On each coverage estimate field, check that:
- There are no arrows on the right side of the field
- Step size is still enforced on the input (whole integers for the first two fields, step of 0.01 for last field)
4. Ensure form can be submitted successfully after all input validation met
Before:
After:
…
> bug/FP-1977: Remove scroll wheels from numeric input fields

- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
- apcd-cms/src/apps/utils/static/utils/js/checkForBlankInputs.js
- apcd-cms/src/taccsite_cms/custom_app_settings.py
…
- [FP-1985](https://jira.tacc.utexas.edu/browse/FP-1985)
- [FP-1974](https://jira.tacc.utexas.edu/browse/FP-1974)
- [FP-1976](https://jira.tacc.utexas.edu/browse/FP-1976)
…
- Added `.js` script for checking an `<input>` for spaces only, and resetting said `<input>`'s value to nothing so the tag's `required` prop can catch it
- Registered `utils` as custom app for above JS script
- Implemented whitespace check on registration form
…
1. Load http://localhost:8000/register/request-to-submit/
2. Fill out form as normal, but fill some text-only inputs with spaces, and try to submit form
3. Confirm form does not successfully submit, and instead redirects back to first field filled with spaces & that said field is now blank (ie with <i>no</i> spaces)
4. Continue trying to submit (depending on …
> task/FP-1985: Util function for checking inputs for whitespace only

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_other_form.html
- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
To audit form fields to make sure they're not only whitespace submissions
- [FP-1974](https://jira.tacc.utexas.edu/browse/FP-1974)
- [FP-1976](https://jira.tacc.utexas.edu/browse/FP-1976)
- Used Garrett's script in the other-exception, threshold-exception and extension form template
- Used script on textareas as well so that if more textarea fields are added in the future (besides justification), it will check those as well
1. In Exception/views.py add the following snippet to the line 105 and 37
<details>
submitters = [ (2, 'TESTGOLD', 10000001, 'gmunoz1', 'CHCD'), (3, 'TESTGOLD', 10000002, 'gmunoz1', 'CHCD'), (1, 'TESTGOLD', 10000000, 'gmunoz1', 'CHCD') ]
</details>
2. Go to  [http://localhost:8000/submissions/threshold-exception/](http://localhost:8000/submissions/threshold-exception/) …
> bug/FP 1974 and 1976 No Whitespace Input on Excp/Ext Forms

- apcd-cms/src/apps/utils/utils.py
- apcd-cms/src/apps/view_users/templates/view_users.html
- apcd-cms/src/apps/view_users/urls.py
- apcd-cms/src/apps/view_users/views.py
Moved view users data filtering to view to accommodate upcoming pagination on page
…
- [WP-19](https://jira.tacc.utexas.edu/browse/WP-19)
- [WP-10](https://jira.tacc.utexas.edu/browse/WP-10)
…
- Pared down filter function in template to grab selected filter and pass back to view via XML request
- Added new user object value to remove parentheses from organization names (replicate filter check already happening on this page)
- Filtering data in view based on url parameter passed from template
- Moved filter options to view for setting up dropdown option as currently selected filter
- Added url pattern to `view-users/urls.py` which accommodates filter url parameter
- Edited filter util function to check for filter substring in queried category data 
…
1. Replace line 12 of …
> task/WP-19: VIew users filtering in view rather than in template

- apcd-cms/src/apps/components/paginator/templates/paginator.html
- apcd-cms/src/apps/submissions/templates/list_submissions.html
- apcd-cms/src/apps/submissions/urls.py
- apcd-cms/src/apps/submissions/views.py
- apcd-cms/src/apps/utils/utils.py
Added filtering by submission status and sorting by date to the user submissions page.
…
- [WP-8](https://jira.tacc.utexas.edu/browse/WP-8)
…
- Added dropdown elements for filter and sort on page's template
- Added JS scripts on template to pass selected filter and/or sort to page's view
- Added sort and filter capability to view to modify data from url parameters
- Added needed url patterns to accommodate both url parameters
- Added check to paginator to look for this component's query string 
…
1. Replace line 29 of `submissions/views.py` with the following:
submission_content = [
{
'submission_id': None,
'submitter_id': None,
'file_name': None,
'status': None,
'outcome': None,
'received_timestamp': None,
'updated_at': None,
'view_modal_content': None …
> task/WP-8: Add filtering and date-sorting to user's View Submissions

- apcd-cms/src/apps/admin_submissions/templates/list_admin_submissions.html
- apcd-cms/src/apps/admin_submissions/urls.py
- apcd-cms/src/apps/admin_submissions/views.py
Added filtering by status and date-sorting to admin submissions page to parallel user submissions page
…
- [WP-7](https://jira.tacc.utexas.edu/browse/WP-7)
…
- Added dropdown elements for filter and sort on page's template
- Added JS scripts on template to pass selected filter and/or sort to page's view
- Added sort and filter capability to view to modify data from url parameters
- Added needed url patterns to accommodate both url parameters
…
1. Replace line 25 of `admin-submissions/views.py` with the following:
submission_content = [
{
'submission_id': None,
'submitter_id': None,
'file_name': None,
'status': None,
'outcome': None,
'received_timestamp': None,
'updated_at': None,
'view_modal_content': None
},
{
'submission_id': 2,
'submitter_id': 1, …
> task/WP-7:  Admin submissions filtering and date-sorting

- apcd-cms/src/apps/utils/apcd_database.py
…
…
- Removed trailing comma before FROM in SELECT command for registration entities
…
1. Nothing to test locally; I tested the current query + the fixed query on QA machine with database and replicated the error and confirmed this fix resolves the issue.
…
> Fix: Syntax error in registration entities util function

- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
…
…
- On registration form (for new registration, not edit), modified values of `option` elements to match codes from standard codes table
…
1. Nothing to test locally; confirmed on QA and standard codes table that these codes are correct
…
> fix: Add correct codes for org type to reg form template

- apcd-cms/src/apps/view_users/templates/view_users.html
- apcd-cms/src/apps/view_users/views.py
…
…
- Instead of removing duplicates in the filter dropdown in the template, now preventing duplicates in the list which populates said dropdown in the page's view
…
1. Replace line 12 of `view_users/views.py` with the following:
user_content = [
(
6,
4,
'[aw@heck.org](mailto:aw@heck.org)',
'Jon Heck',
'UHC & Nop',
'no create',
'none update',
'no notes',
'True',
7,
'submitter'
),
(
6,
4,
'[aw@snow.org](mailto:aw@heck.org)',
'Jon Snow',
'UHC & Nop',
'no create',
'none update',
'no notes',
'True',
11,
'submitter'
),
(
5,
4,
'[aw@heck.org](mailto:aw@heck.org)',
'Alex Hamilton',
't and (t)',
'no create',
'none update',
'no notes',
'True',
8,
'submitter',
),
(
5,
4,
'[aw@heck.org](mailto:aw@heck.org)',
'Penny Ante',
'UHC',
'no create',
'none update',
'no …
> Fix: View users org dropdown not consistently populating with selected organization

- apcd-cms/src/apps/admin_regis_table/views.py
…
…
- Removed `dateutil parser.parse` function from date processing from database
…
1. Replace lines 70-72 in `apps/admin_regis_table/views.py` with the following:
(76, datetime.date(2022, 10, 24), 202210, 202302, True, 'complete', 'carrier', 'GlobalHealth of Texas, Inc.', '210 Park Avenue, Suite 2800', 'Oklahoma City', 'OK', '73102     '),
(77, datetime.date(2022, 10, 24), 202210, 202302, True, 'complete', 'carrier', 'Golden Rule Insurance Company', '7440 Woodland Drive', 'Indianapolis', 'IN', '46278     '),
(78, datetime.date(2022, 10, 24), 202210, 202302, True, 'complete', 'carrier', 'Molina Healthcare of Texas', '1660 Westridge Circle North', 'Irving', 'TX', '75038     '),
(86, datetime.date(2022, 11, 1), …
> fix: Registration listing - dates incorrectly parsed

- apcd-cms/Dockerfile
- matcssi_cms/Dockerfile
Install Core-CMS v3.11 on APCD and MATCSSI.
- [TUP-506](https://jira.tacc.utexas.edu/browse/TUP-506)
- **changed** Dockerfile CMS tags
1. Deploy.
2. Verify no change.
These will also be tested via [2023-06-15 CMS Testing Session (v3.11)](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=295996153).
Skipped. Zero change expected and noticed.
> test(apcd, matcssi): core-cms v3.11

- apcd-cms/src/apps/utils/apcd_database.py
Changed db query for admin submission listing page to show org name from submitters table rather than from apcd_orgs table
…
- [WP-184](https://jira.tacc.utexas.edu/browse/WP-184)
- [WP-187](https://jira.tacc.utexas.edu/browse/WP-187)
…
- In db util function for this page, joined `submitters` table to `submission` table to access `submitterss.org_name`
…
1. Open http://localhost:8000/administration/list-submissions/
2. Confirm that, in 'Organization' column, 'TACC Test' now displays instead of 'chcd'
Before:
After:
…
Thank you @happycodemonkey for writing the revised table query here!
> bug/WP-184: Admin submissions listing page showing wrong org name

- tapisproject_cms/Dockerfile
Fix accent color via new CMS image.
- [WI-6](https://jira.tacc.utexas.edu/browse/WI-6)
- relies on https://github.com/TACC/Core-CMS/releases/tag/v3.11.2
- also includes https://github.com/TACC/Core-CMS/releases/tag/v3.11.3
- **changed** cms image
0. Deploy.
1. Verify accent color is changed.
2. Verify no other style changes occur.*
<sup>\* Content differences are independent of this code change.</sup>
| v3.N<br><sup>tapis-project.org</sup> | v3.9<br><sup>\*.tapisproject.…</sup> | v3.11<br><sup>\*.tapisproject.…</sup> | fixed<br><sup>(this pull request)</sup> |
| - | - | - | - |
| ![live-tapis--v3-N](https://github.com/TACC/Core-CMS-Custom/assets/62723358/cc0e07a5-3be5-4b62-90b9-7fe89cdbdfb0) | ![prod-tapis--v3-9-0](https://github.com/TACC/Core-CMS-Custom/assets/62723358/92f439f5-b26c-4970- …
> fix(tapis): CMS v3.11.2 accent color via v3.11.3

- tapisproject_cms/Dockerfile
Use official https://github.com/TACC/Core-CMS/releases/tag/v3.11.4 instead of candidate.
- follow-up to #181
https://pprd.tapisproject.tacc.utexas.edu/
> chore(tapis): CMS v3.11.4

- apcd-cms/src/apps/admin_exception/views.py
- apcd-cms/src/apps/admin_extension/views.py
- apcd-cms/src/apps/admin_regis_table/views.py
- apcd-cms/src/apps/admin_submissions/templates/list_admin_submissions.html
- apcd-cms/src/apps/admin_submissions/urls.py
- apcd-cms/src/apps/admin_submissions/views.py
- apcd-cms/src/apps/components/paginator/templates/paginator.html
- apcd-cms/src/apps/submissions/templates/list_submissions.html
- apcd-cms/src/apps/submissions/urls.py
- apcd-cms/src/apps/submissions/views.py
- apcd-cms/src/apps/view_users/views.py
For consistency and simplicity across listing pages, updated order for url parameters passed to paginator
…
- [WP-88](https://jira.tacc.utexas.edu/browse/WP-88)
…
- On paginator, now the page # is passed first in paginator buttons, and any filters are tagged on the end via context variable in each view
- In each view for listing pages, updated to read any non-page # to a context variable `query_str` for above
- For user and admin submissions, renamed status filter vars & url param to be consistent with other pages 
…
1. On each listing page (urls listed below), check that:
- Filter(s) function correctly (selected option populates drop down default value on page reload, url parameter populates in url)
- Paginator functions normally
- Both paginator and filters work correctly together
- …
> task/WP-88: URL Parameters reordering w/ paginator

- apcd-cms/src/apps/admin_exception/templates/list_admin_exception.html
- apcd-cms/src/apps/admin_extension/templates/list_admin_extension.html
- apcd-cms/src/apps/admin_extension/views.py
To fix bug on extension admin table so that org filter displays All first and doesn't assign it to the first alphabetized org name.
- [WP-199](https://jira.tacc.utexas.edu/browse/WP-199)
-Created function in extension admin view so that the view doesn't sort All as it iterates through and sorts organization names
- Removed empty drop down choice in org filter for both exceptions and extensions. No longer needed.
1. Go to [http://localhost:8000/administration/list-extensions/]( http://localhost:8000/administration/list-extensions/)
2. Make sure that All is first on the list. Can test with stache production creds to see that All is no longer alphabetized.
3. Go to [http://localhost:8000/administration/list-exceptions/](http://localhost:8000/administration/list-exceptions/)
4. Make sure that …
> Updated extension admin org filter to display all first

- apcd-cms/src/apps/admin_exception/views.py
- apcd-cms/src/apps/admin_extension/views.py
Fixing a bug where the exceptions and extensions were not sorting by created date when no filters were selected
- [WP-218](https://jira.tacc.utexas.edu/browse/WP-218)
Updated view that shows admin exception and extension records so that it is sorted by the correct field in the database (created_at)
1. Go to [http://localhost:8000/administration/list-exceptions/](http://localhost:8000/administration/list-exceptions/ )
2. Make sure they're listed in order from created at column. 
3. Create a new exception and make sure it is the first on the admin list
4. Go to [http://localhost:8000/administration/list-extensions/](http://localhost:8000/administration/list-extensions/and) select Edit Record from Action drop down
2. Make sure they're listed in order from created at column. 
3. Create a new …
> Sorting by incorrect date field for exceptions and extensions

- a2cps_cms/Dockerfile
- apcd-cms/Dockerfile
- demdata_cms/Dockerfile
- matcssi_cms/Dockerfile
- tapisproject_cms/Dockerfile
Use image for Core-CMS since:
- https://github.com/TACC/Core-CMS/pull/697
- similar to https://github.com/TACC/Core-Portal-Deployments/pull/26
- similar to PR yet to be made
- **changed** all Core-CMS image tags — updated each to latest patch version
1. Build each.
2. Deploy each to test server.
> hotfix: cms v3.12.0-beta

- apcd-cms/src/apps/submissions/urls.py
- apcd-cms/src/apps/submissions/views.py
- apcd-cms/src/taccsite_cms/custom_app_settings.py
- apcd-cms/src/taccsite_cms/urls_custom.py
Adding back check submitter role endpoint for prod APCD
…
…
- Added relevant endpoint and view back to submissions custom app
- Added submissions custom app back to Django registry
…
1. N/A
…
> hotfix: Check submitter role restored in prod

- docs/port-project.md
Remind devs porting a project to update Portal favicon, if relevant.
- similar to 
- **added** sub-section to porting doc
1. Open https://github.com/TACC/Core-CMS-Custom/blob/docs/portal-favicon-when-porting/docs/port-project.md#has-a-core-portal.
2. Read words.
3. Test links.
> docs: don't forget portal favicon when porting

- README.md
- docs/port-project.md
Reference new project upgrade doc from https://github/com/TACC/Core-CMS.
- requires https://github.com/TACC/Core-CMS/pull/723
- **added** link to new Core-CMS `upgrade-project.md` in `README.md`
- **added** link to new Core-CMS `upgrade-project.md` in `port-project.md`
- **changed** formatting and sections for CSS gotchas in `port-project.md`
> docs: reference core-cms upgrade doc

- apcd-cms/src/apps/registrations/views.py
- apcd-cms/src/apps/submitter_renewals_listing/templates/list_submitter_registrations.html
- apcd-cms/src/apps/submitter_renewals_listing/views.py
With passing reg_id as a url parameter to the registration form to initiate a renewal, need to check both user role and reg_id validity for said user before a renewal can be initiated on the form.
- [WP-347](https://jira.tacc.utexas.edu/browse/WP-347)
…
- If `reg_id` parameter is in GET request for the registration form, now also checks if a user if either a submitter admin or an APCD admin
- Then grabs user's submitter code and checks if queried `reg_id` is within submitter code's registrations before loading registration's data to the form
- If any of the above tests are not passed, instead loads registration form with no pre-loaded data
- Some code clean-up + linting found while working on main task 
…
1. Go to http://localhost:8000/admin and:
- Go to click users and your username
- …
> task/WP-347: Restrict registration renewal access

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_other_form.html
- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
- apcd-cms/src/apps/exception/views.py
- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
- apcd-cms/src/apps/extension/views.py
- apcd-cms/src/apps/utils/apcd_database.py
This PR changes the business name options on the exception and extension forms from org_name - submitter ID on submitter table to entity_name - payor code on submitter table.
Also now allows threshold exceptions to choose from different business names (entity - payor codes) associated with their user name.
- [WP-349](https://jira.tacc.utexas.edu/browse/WP-349)
- [WP-350](https://jira.tacc.utexas.edu/browse/WP-350)
Exceptions
- Moved business name to each of the threshold exception blocks. Changed the drop down to prepopulated entity names - payor codes
- Changed create_threshold_extension insert so that it gets a business name for each block. 
- ThresholdExceptionView will associate each insert with a unique payor code, entity, submitter_id based on user's business name selection …
> Task/WP 349 350 Business name change exten excep forms

- apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/css/table.css
- apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
- apcd-cms/src/apps/admin_regis_table/views.py
- apcd-cms/src/apps/registrations/static/registrations/css/submission_form.css
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
- apcd-cms/src/apps/registrations/views.py
- apcd-cms/src/apps/submitter_renewals_listing/templates/list_submitter_registrations.html
- apcd-cms/src/apps/submitter_renewals_listing/views.py
- apcd-cms/src/apps/utils/apcd_database.py
Addresses requested changes to entities on the registration form + adds 'Year' column to admin registration listing
…
- [WP-345](https://jira.tacc.utexas.edu/browse/WP-345)
- [WP-376](https://jira.tacc.utexas.edu/browse/WP-376)
…
**WP-345**
- For file type checkboxes, now at least one of three (Medical, Pharmacy, Dental) must be selected to continue to submit form
- Entity coverage estimate fields are now text fields which only accept ints or float (where needed) by regex patterns
- Slightly increased state box to accommodate larger state abbreviations + added JS listeners to swap between state abbr. and full name, depending on user interaction on drop down
**WP-376**
- Added 'Year' column to admin list registrations table
- Consolidated styling for registrations listings to one CSS file …
> task/WP-345: Entities changes UTH & task/WP-376: Add 'Year' column to registration admin listing

- apcd-cms/src/apps/admin_regis_table/templates/view_registration_modal.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd-cms/src/apps/utils/apcd_database.py
- apcd-cms/src/apps/utils/registrations_data_formatting.py
Per UTH, now allow user to write in registration year on registration form
…
- [WP-383](https://jira.tacc.utexas.edu/browse/WP-383)
…
- Added `input type=number` field for Registration Year on registration form, with min value of `2023`
- On create and update registration db functions, changed value written to database for `registration_year` to value from form
- Added 'Registration Year' field to view registration modal + corresponding Django context object
…
1. Go to https://localhost:8000/register/request-to-submit
2. Check for new field "Registration Year" on top of form, and ensure it accepts no values other than int values starting at 2023
3. On successful submit of form, go to https://localhost:8000/administration/list-registration-requests and confirm your record is on the table …
> task/WP-383: Allow user input of registration year

- apcd-cms/src/apps/registrations/static/registrations/css/submission_form.css
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
A couple of updates for the registration form from our 11-09-23 testing session
…
- [WP-381](https://jira.tacc.utexas.edu/browse/WP-381)
- [WP-382](https://jira.tacc.utexas.edu/browse/WP-382)
…
- On entities, NAIC and License input fields are now text input fields w/ regex that only allows ints to be submitted
- For state dropdown, removed all JS + CSS on this select to now show full state abbr + state name
…
1. Go to https://localhost:8000/register/request-to-submit
2. Fill out form, and ensure:
- The state dropdown is now the same length as the fields above it, and displays the states as so: "[State abbr.] - [State name" i.e. "TX - Texas"
- The NAIC and License fields on more than 1 entity entry only allow ints to be submitted
3. Submit form, and on success, go to …
> task/WP-381 and WP-382: Reg form updates

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_other_form.html
- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
- apcd-cms/src/apps/view_users/templates/view_user_edit_modal.html
Follow-on task to fix broken regex on multiple forms' email validation
…
- [WP-327](https://jira.tacc.utexas.edu/browse/WP-327)
- [WP-330](https://jira.tacc.utexas.edu/browse/WP-330)
…
- On exception threshold + other as well as extension forms, escaped the `-` within the regex character fields on the email inputs to resolve broken regex pattern
- On view user edit modal, converted username + email fields to text input to allow regex validation, and included regex pattern used for email on other forms for this field
…
1. Go to http://localhost:8000/submissions/extension-request/
2. Fill out form, and test email field to ensure pattern of "[some input]@[someinput].[some input]" is enforced
3. Check dev console and confirm no errors about regex characters is showing
4. Repeat steps 2 + 3 …
> bug/WP-327: Broken email regex

- ecep_cms/src/taccsite_cms/urls_custom.py
[Use `re_path`, not `url`, since Django 4.](https://docs.djangoproject.com/en/3.2/ref/urls/#url)
<details><summary>the error that this fixes</summary>
```
django.urls.exceptions.NoReverseMatch: Reverse for 'taggit_autosuggest-list' not found. 'taggit_autosuggest-list' is not a valid view function or pattern name.
```
</details>
- [RT #27486](https://tickets.tacc.utexas.edu/Ticket/Display.html?id=27486)
Try to edit a blog article on ECEP site with this fix deployed.
| before | after |
| - | - |
| <img width="1006" alt="before" src="https://github.com/TACC/Core-CMS-Custom/assets/62723358/a3409b52-cfab-43e0-8e39-652a23b51d4e"> | <img width="1006" alt="after" src="https://github.com/TACC/Core-CMS-Custom/assets/62723358/696228d5-75de-4f5c-bf19-ff068aad58a1"> |
> hotfix: fix 500 error of "taggit_autosuggest-list"

- a2cps_cms/Dockerfile
- matcssi_cms/Dockerfile
Moving portal to latest version of CMS to upgrade django. The current version of django in A2CPS and MISE is 3.x.
[WP-132](https://jira.tacc.utexas.edu/browse/WP-132) requires https://github.com/TACC/Core-CMS/releases/tag/v4.5.0
Upgrade to 4.5.0
Will do testing once a version is deployed to pprd sites.
> Task/WP-132 upgrade django version in A2CPS and MISE

- apcd-cms/src/apps/extension/templates/extension_submission_form/extension_form_success.html
- apcd-cms/src/apps/utils/apcd_database.py
Submitter calendar can accept duplicates by db design, but non functional in use cases. Business logic / queries need to adjust to that.
The key fields in submitter_calendar are submitter_id, data_period_start. 
Submitter_id is distinct for each submitter (org, payor_code). There is no other information in submitter_calendar to derive uniqueness. With the current db design, it is safe to assume the data_period_start should be unique per submitter_id.
If any of the business logic needs to change, that will require db design change.
[WP-483](https://tacc-main.atlassian.net/browse/WP-483)
* For time period use distinct
* Change button text to go to dashboard
1. Uploaded duplicate rows in test DB:
`select calendar_item_id, submitter_id, data_period_start, expected_submission_date from …
> Bug/WP-483 - APCD fixes for extensions

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
Exception request form - remove incomplete statement.
There is extra text "I accept on the behalf of.." which is not relevant for exception threshold form.
…
[WP-484](https://tacc-main.atlassian.net/browse/WP-484)
Delete text from form.
1. Threshold exception form
2. Other exception form (unchanged)
> Bug/WP-484: Remove text from threshold form

- .github/pull_request_template.md
PR template is suggesting old (thus broken) links be created. This fixes those URLs.
- noticed in #270
> docs(.github): PR template should ref. tacc-main not jira

- apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html
…
- [WP-326](https://tacc-main.atlassian.net/browse/WP-326)
…
- To helper text script, added lines to point to and then update `max` prop on requested threshold input for each threshold exception block
…
1. Go to https://localhost:8000/submissions/threshold-exception/
2. On the 'Requested Threshold Reduction' portion, choose options for File Type, Field Code, and Expiration Date
3. On the 'Requested Threshold Percentage' field, ensure you cannot submit the form with a value greater than that shown in the helper text below said field
4. Repeat for at least one other Threshold Exception block (via 'add Another Threshold Exception')
5. Complete form and submit, then go to https://localhost:8000/administration/list-exceptions/ and confirm your new exceptions show up and have the correct info …
> bug/WP-326: Threshold exception - validator doesn't match helper text on requested threshold

- apcd-cms/src/apps/admin_regis_table/views.py
…
- [WP-495](https://tacc-main.atlassian.net/browse/WP-495)
…
- Now using `datetime.date` method to sub in date 01-01-0001 for None date entries instead of dateutil's `parser.parse`
…
1. Ensure your local instance for APCD is pointing to the 'apcd-psql-test' db in your local settings
2. Go to https://localhost:8000/administration/list-registration-requests
3. Confirm that the page loads successfully and that there is a record with name 'Tracy Test Busn' as the last record on the last page of the listing (this is the record with 'posted_date' as NULL)
…
> bug/WP-495: Proxy date for 'None' posted_date on registrations using wrong data type

- apcd-cms/src/taccsite_cms/custom_app_settings.py
The static file specification in settings is wrong leading to [build errors](https://jenkins01.tacc.utexas.edu/view/WMA%20CEP/job/Core_Portal_Deploy/3859/consoleFull) like this:
```
?: (staticfiles.W004) The directory 'taccsite_custom/apcd-cms' in the STATICFILES_DIRS setting does not exist.
```
- [WP-522](https://tacc-main.atlassian.net/browse/WP-522)
Fix the path specified in config
1. Run build
…
> WP-522: Fix incorrect path for STATICFILE_DIRS

- netsage_cms/Dockerfile
…
…
- Updated core-cms image to v4.8.0
…
1. Deployed to [NetSage PPRD](https://pprd.netsage.tacc.utexas.edu/)
…
> task/WP-452: Upgrade Netsage CMS to Django 4.2+

- apcd-cms/docker-compose.dev.yml
- apcd-cms/src/apps/admin_submissions/templates/list_admin_submissions.html
- apcd-cms/src/apps/admin_submissions/urls.py
- apcd-cms/src/apps/admin_submissions/views.py
- apcd-cms/src/apps/utils/apcd_database.py
- apcd-cms/src/client/package-lock.json
- apcd-cms/src/client/package.json
- apcd-cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
- apcd-cms/src/client/src/components/Admin/Submissions/ViewSubmissionLogsModal.tsx
- apcd-cms/src/client/src/components/Admin/Submissions/index.ts
- apcd-cms/src/client/src/components/library.tsx
- apcd-cms/src/client/src/hooks/admin/index.ts
- apcd-cms/src/client/src/hooks/admin/useAdmin.ts
Converted the Admin Submissions page to a react component. Added `reactstrap` package to the project which allows us to use additional components. Added use of the reactstrap Modal component to handle modals. This is the same component that tup uses as well 
- [WP-443](https://tacc-main.atlassian.net/browse/WP-443)
- requires https://github.com/TACC/Core-CMS/pull/117
- Added `AdminSubmissions.tsx` which contains logic for the main Admin Submissions page including Filter and Sort
- Added `ViewSubmissionsLogsModal.tsx` which uses reactstrap modal and displays the logs for a submission
- Fixed a bug in the sql query for submissions which should now return an empty array of logs if none exist
1. Run `npm run install` and `npm run build` in the client directory 
2. Start the server with the …
> task/WP-443 Convert Admin Submissions to React

- apcd-cms/Makefile
Docker v2 has different commandline for compose `docker compose`
Adjust Makefile to handle both based on availability
[WP-602](https://tacc-main.atlassian.net/browse/WP-602)
Add command var based on whether `docker-compose` works
1. Update to v2.
2. cd to apcd_cms
3. make build
4. make start
> Adapt Makefile for docker v2

- apcd-cms/src/apps/admin_exception/templates/list_admin_exception.html
- apcd-cms/src/apps/admin_exception/urls.py
- apcd-cms/src/apps/admin_exception/views.py
- apcd-cms/src/client/src/components/Admin/Exceptions/AdminExceptions.tsx
- apcd-cms/src/client/src/components/Admin/Exceptions/index.ts
- apcd-cms/src/client/src/hooks/admin/index.ts
- apcd-cms/src/client/src/hooks/admin/useAdmin.ts
- apcd-cms/src/client/src/main.tsx
First pass at updating Admin List Exceptions page to React. No API work has been done yet and is still lacking dropdown functionality.
[WP-441](https://tacc-main.atlassian.net/browse/WP-441)
Listing page converted to React component.
1. Go to http://localhost:8000/administration/list-exceptions/ and make sure its listing exceptions information.
The modal windows related to the "Actions" dropdown in the exceptions rows are not been implemented in this PR.
> List Admin Exceptions React Conversion

- demdata_cms/Makefile
- ecep_cms/Makefile
- example_cms/Makefile
Docker v2 has different command for `docker compose`. Adjust Makefile to handle both based on availability.
- [WP-602](https://tacc-main.atlassian.net/browse/WP-602)
- mimics https://github.com/TACC/Core-CMS-Custom/pull/295
- **added** conditional `docker compose` command to Makefile
1. `make build` — no error firing command from Makefile
2. `make start` — no error firing command from Makefile
Skipped.
> fix: WP-602 `docker compose` with and without dash

- apcd_cms/src/apps/admin_regis_table/views.py
Incorrect index is being used to populate org dropdown, this pull request fixes this issue.
…
[WP-687](https://tacc-main.atlassian.net/browse/WP-687)
Updated index on ln 94 on the admin_regis_table/views.py file
1. Navigate to http://localhost:8000/administration/list-registration-requests/ and verify the "Filter by Organization" dropdown is being correctly populated by organizations.
2. Verify dropdown is filtering properly
…
> WP-687: Hotfix: Org dropdown being mistakenly populated by city

- apcd_cms/src/apps/registrations/templates/submission_form/registration_form_body.html
- apcd_cms/src/apps/utils/apcd_database.py
…
- [WP-695](https://tacc-main.atlassian.net/browse/WP-695)
…
- Adds new `<select>` element to registration form, only rendered if registration data is being loaded to the form + is not a registration renewal
- Adds write to `registration_status` field on registrations table on database for `update_registration` db util function 
…
1. Go to http://localhost:8000/administration/list-registration-requests/
2. Select a record to edit via Actions column -> "Edit Record"
3. Confirm that a new drop down labeled 'Registration Status' appears at the top of the 'Organization' portion of the form
4. Confirm this drop down's pre-selected value matches that in the 'Registration Status' column for the same record on the table
5. Select a different option in the drop down and then submit that change
6. …
> task/WP-695: Add status change to edit registration modal

- apcd_cms/src/apps/admin_regis_table/views.py
…
- [WP-695](https://tacc-main.atlassian.net/browse/WP-695)
…
- Adds 'Withdrawn' to status options for admin registrations listing + edit record modal 'Registration Status' field
…
1. Go to http://localhost:8000/administration/list-registration-requests/
2. Confirm that the 'Status' filter on the page now has 'Withdrawn' as an additional option
3. Confirm the same for the 'Registration Status' field on the 'Edit Record' modal on a record on the table
- Additionally, try updating the value for the record to 'Withdrawn' and submit, confirm it succeeds and, upon reloading the page, this 'Withdrawn' status shows up on the related row for the record and in the same edit record modal
4. Confirm the same for the [submitter admin registrations …
> task/WP-695: Add 'Withdrawn' to status options

- apcd_cms/src/apps/admin_exception/templates/list_admin_exception.html
- apcd_cms/src/apps/admin_exception/views.py
- apcd_cms/src/apps/admin_extension/templates/list_admin_extension.html
- apcd_cms/src/apps/admin_extension/views.py
- apcd_cms/src/apps/admin_regis_table/templates/list_registrations.html
- apcd_cms/src/apps/admin_regis_table/views.py
- apcd_cms/src/apps/admin_submissions/templates/list_admin_submissions.html
- apcd_cms/src/apps/admin_submissions/views.py
- apcd_cms/src/apps/submissions/templates/list_submissions.html
- apcd_cms/src/apps/submissions/views.py
- apcd_cms/src/apps/utils/apcd_database.py
- apcd_cms/src/apps/view_users/templates/view_users.html
- apcd_cms/src/apps/view_users/views.py
- apcd_cms/src/taccsite_custom/apcd_cms/static/apcd_cms/css/table.css
Checks for null for filter options for listings in admin listing tables and user submission table.
[WA-349](https://tacc-main.atlassian.net/browse/WA-349)
…
1. Checkout main then pull this branch
2. Go to each listing page and make sure they're listed alphabetically and sorted correctly.
- http://localhost:8000/submissions/list-submissions/
- http://localhost:8000/administration/list-registration-requests/
- http://localhost:8000/administration/view-users/
- http://localhost:8000/administration/list-exceptions/
- http://localhost:8000/administration/list-extensions/
- http://localhost:8000/administration/list-submissions/
3. Toggle filters and make sure they work correct (known race conditions if you change them too quickly before load)
4. Review code to check for consistency and null …
> hotfix/address-null-in-filters 

- apcd-cms/src/apps/view_users/views.py
The list of org names is derived from actual data.
- [WP-711](https://tacc-main.atlassian.net/browse/WP-711)
* Adjust the `view-users/api/options`  to read from DB.
* Since option api is available, remove the hard coded list from actual data.
1.http://localhost:8000/administration/view-users/?org=None
> Bug/WP-711: Do not use hardcoded org names for user list

- apcd-cms/src/apps/admin_regis_table/urls.py
- apcd-cms/src/apps/admin_regis_table/views.py
- apcd-cms/src/apps/submitter_renewals_listing/urls.py
- apcd-cms/src/apps/submitter_renewals_listing/views.py
- apcd-cms/src/apps/utils/apcd_database.py
- apcd-cms/src/apps/utils/registrations_data_formatting.py
- apcd-cms/src/client/src/components/Admin/Registrations/AdminRegistrations.tsx
- apcd-cms/src/client/src/components/Forms/Registrations/RegistrationForm.tsx
- apcd-cms/src/client/src/components/Forms/Registrations/index.ts
- apcd-cms/src/client/src/components/Registrations/EditRegistrationModal/EditRegistrationModal.tsx
- apcd-cms/src/client/src/components/Registrations/RegistrationList/RegistrationList.tsx
- apcd-cms/src/client/src/components/Registrations/ViewRegistrationModal/ViewRegistrationModal.tsx
- apcd-cms/src/client/src/hooks/registrations/index.ts
- apcd-cms/src/client/src/hooks/registrations/useForm.ts
- apcd-cms/src/client/src/hooks/registrations/useRegistrations.ts
With RegistrationForm available, hookup edit registration and renew registration to it.
Reuse as much of the component code as possible.
- [WP-738](https://tacc-main.atlassian.net/browse/WP-738)
* Make RegistrationForm adaptable to edit and also modal 
* Move the registration form submission to a `usePost` with `mutation` to allow invalidating the registration listing when an edit is done.
* Do not load all the registration modal content for listing page. Only load on demand. This is both a perf improvement and also to keep data in sync between updates.
* Update submitter listing
* Manage registration listing to allow renew for nonAdmin scenario and update for admin scenario. (different actions).
* Adjust the registration form to handle reg_id form url and make a request.
1. Go to …
> WP-738 Hook up Edit Registration and Renew Registration to Registration Form.

- apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/css/table.css
- apcd-cms/src/client/src/components/Registrations/RegistrationList/RegistrationList.tsx
* Clear selection button is not clear all selections
* Also fix spacing issue on long org names.
* Use common button.
[WP-744](https://tacc-main.atlassian.net/browse/WP-744)
Go to http://localhost:8000/administration/list-registration-requests/
* Select different options for both filters. 
* Clear selection
* the filter value should reset and the data should be accurate.
> WP-744: Registration Table - fix clear selection button

- apcd-cms/src/apps/common_api/views.py
- apcd-cms/src/apps/extension/urls.py
- apcd-cms/src/apps/extension/views.py
- apcd-cms/src/client/src/components/Components/FormLabel/FormLabel.module.css
- apcd-cms/src/client/src/components/Components/FormLabel/FormLabel.tsx
- apcd-cms/src/client/src/components/Submitter/Extensions/ExtensionFormInfo.tsx
- apcd-cms/src/client/src/components/Submitter/Extensions/ExtensionsForm.tsx
- apcd-cms/src/client/src/hooks/entities/index.ts
* Get the applicable dates, and set it accordingly to the entity id.
* Set the max value for extended date
* Set the expected date.
* Wire up the backend for this.
* Write a custom component for Label
* Use required field new look.
- [WP-752](https://tacc-main.atlassian.net/browse/WP-752)
1. Request extension here: http://localhost:8000/submissions/extension-request/ 
2. Enter nothing and see the required field messages
3. Checkout the applicable date periods and date management
4. See the max date.
> WP-752: ExtensionForm expected date fix, required field UI

- apcd-cms/src/client/src/components/Admin/ViewUsers/ViewUsers.tsx
* Remove clear options button when the filters are default. This matches prod behavior
[WP-750](https://tacc-main.atlassian.net/browse/WP-750)
1. Go to http://localhost:8000/administration/view-users/
and test clear options behavior
> View Users: clear options button behavior

- apcd-cms/src/client/src/components/Admin/EditExceptionModal/EditExceptionModal.tsx
- apcd-cms/src/client/src/components/Admin/ViewExceptionModal/ViewExceptionModal.tsx
- apcd-cms/src/client/src/components/Admin/ViewUsers/EditRecordModal.tsx
- apcd-cms/src/client/src/components/Admin/ViewUsers/ViewRecordModal.tsx
- apcd-cms/src/client/src/components/Extensions/EditExtensionModal/EditExtensionModal.tsx
- apcd-cms/src/client/src/components/Extensions/ViewExtensionModal/ViewExtensionModal.tsx
- apcd-cms/src/client/src/components/Registrations/EditRegistrationModal/EditRegistrationModal.tsx
- apcd-cms/src/client/src/components/Registrations/ViewRegistrationModal/ViewRegistrationModal.tsx
Modal close icon is broken after styles update.
[WP-756](https://tacc-main.atlassian.net/browse/WP-756)
1. Use times
2. be consistent on modal header.
1. Go to http://localhost:8000/administration/list-registration-requests/ and checkout view and edit modal.
2. Same for http://localhost:8000/administration/view-users/
3. And http://localhost:8000/administration/list-exceptions/
> bugs/WP-756: [APCD][React] Fix modal close button

- apcd-cms/src/client/src/components/Admin/Exceptions/AdminExceptions.tsx
- apcd-cms/src/client/src/components/Admin/Extensions/AdminExtensions.tsx
- apcd-cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
- apcd-cms/src/client/src/components/Admin/ViewUsers/ViewUsers.tsx
- apcd-cms/src/client/src/components/Submissions/ViewFileSubmissions/ViewSubmissions.tsx
…
- [WP-324](https://tacc-main.atlassian.net/browse/WP-324)
…
- Puts a wrapper around table rows that checks if there is any row data in the response, otherwise displays a message reading 'No Data available' (from registrations listing)
…
1. Go to each listing (excluding registrations listings) and use the following filter combos to check if the 'No Data available':
- Admin Exceptions: Status to 'Pending', Organization to 'Uthealth - Sph Chcd: Apcd'
- Admin Extensions: Couldn't find a combo as only one org on local db, can skip
- Admin Users: Status to 'Active', Org to 'UTHealth - SPH CHCD: APCD'
- Admin Submissions: Couldn't find a combo as only one filter + all statuses present on table, can skip
- User Submissions: Dependent on if you have attempted submissions on dev DB, try toggling …
> task/WP-324: Add message for no data to show in listing tables

- apcd_cms/src/apps/admin_submissions/views.py
JSON is interpreted and not treated as string when downloading.
[WP-777](https://tacc-main.atlassian.net/browse/WP-777)
1. cast contents as str.
1. Download html and json logs and **view contents** in http://localhost:8000/submissions/list-submissions/
2. Repeat it in admin view: http://localhost:8000/submissions/list-submissions/
> WP-777  - json download issue

- apcd_cms/src/apps/admin_exception/urls.py
- apcd_cms/src/apps/admin_extension/urls.py
- apcd_cms/src/apps/admin_regis_table/urls.py
- apcd_cms/src/apps/registrations/urls.py
- apcd_cms/src/apps/submitter_renewals_listing/urls.py
- apcd_cms/src/apps/view_users/urls.py
Several of our URLs contains regular expressions (or regexes) that passed in variables when a user sorted any of the tables by a given variable. This was throwing warnings in back-end terminals as well as Docker.
- [WP-387](https://tacc-main.atlassian.net/browse/WP-387)
I replaced all instances of `r'(?P<variable>'` with `'<variable>'` from Django's `urls.path` library in order to continue to pass in these variables. 
1. Log in as an Admin as usual.
2. Fire up the containers as usual.
3. Navigate to any page containing (for example, Admin > List Registration Requests).
4. Toggle either dropdown menu to anything other than its default value.
5. Notice in the back-end terminal or Docker that there are no more warnings!
> Task/WP-387: Remove regex from path URLs

- apcd_cms/src/apps/utils/apcd_database.py
1) Provide 404 error when log is null.
2) Also, currently the download log link is not available if log is null.
[WP-793](https://tacc-main.atlassian.net/browse/WP-793)
1. Update sql to do null check.
1. Go to http://localhost:8000/administration/view_log?log_type=html&log_id=290 to see 404.
2. Download a valid log at http://localhost:8000/administration/list-submissions/ to check for regressions
> WP-793: When log is null, handle issue gracefully instead of 500

- apcd_cms/src/apps/admin_extension/views.py
- apcd_cms/src/apps/common_api/urls.py
- apcd_cms/src/apps/common_api/views.py
- apcd_cms/src/apps/utils/apcd_database.py
- apcd_cms/src/client/src/components/Extensions/EditExtensionModal/EditExtensionModal.tsx
- apcd_cms/src/client/src/hooks/entities/index.ts
- apcd_cms/src/client/src/hooks/entities/useEntities.ts
Fixes the following issues:
1. Remove references to `Exception` and `Users` in the labels and code.
2. After error, clear it when re-submitted
3. Disable submit when nothing is edited
4. Date periods are previously retrieved based on what the user has access to, instead get it for the submitter_id - this is admin page, so it should retrieve all available.
[WP-789](https://tacc-main.atlassian.net/browse/WP-789)
1. One significant change is to add new api to retrieve available date period for submitter id.
1. Go to http://localhost:8000/administration/list-extensions
2. Use the edit modal and try the following
* labels are accurate
* submit with bad date and error should go away on resubmit
* submit is disabled if there is no edit
* date periods for extensions that current user did not …
> Bugs/WP-789: Extension Edit Modal

- apcd_cms/src/client/src/components/Admin/Exceptions/AdminExceptions.tsx
- apcd_cms/src/client/src/components/Admin/Extensions/AdminExtensions.tsx
- apcd_cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
- apcd_cms/src/client/src/components/Admin/ViewUsers/ViewUsers.tsx
- apcd_cms/src/client/src/components/ClearOptionsButton/ClearOptionsButton.module.css
- apcd_cms/src/client/src/components/ClearOptionsButton/ClearOptionsButton.tsx
- apcd_cms/src/client/src/components/ClearOptionsButton/index.ts
- apcd_cms/src/client/src/components/Registrations/RegistrationList/RegistrationList.tsx
- apcd_cms/src/client/src/components/Submissions/ViewFileSubmissions/ViewSubmissions.tsx
1) make a custom component and use it in all pages.
[WP-795](https://tacc-main.atlassian.net/browse/WP-795)
1) Custom component
2) core component Button
3) use a style to match filter.
1. Go to all admin pages, submission listing and check for clear filter.
> Bugs/WP-795: clear selection button uniformity

- apcd_cms/src/apps/utils/apcd_database.py
1. Duplicate order by. Remove it.
1. Test http://localhost:8000/administration/list-registration-requests/
2. http://localhost:8000/register/list-registration-requests/
> Quick Fix: APCD, List registrations for submitter is broken

- apcd_cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
Page title should match Nav and say “View File Submissions” then can still have the line of “All submissions by organizations“.
[WP-806](https://tacc-main.atlassian.net/browse/WP-806)
File Submissions title update
1. Navigate to http://localhost:8000/administration/list-submissions/
2. Make sure page title shows 'View File Submissions'
> File Submissions title update

- apcd_cms/src/client/src/components/Submitter/Exceptions/ExceptionFormPage.tsx
…
- [WP-797](https://tacc-main.atlassian.net/browse/WP-123)
…
- Used Yup's min & max functions to restrict dates on both Threshold and Exception forms to format MM/DD/YYYY
…
1. Go to http://localhost:8000/submissions/exception/ and confirm, for both Threshold and Other exceptions, that dates not matching MM/DD/YYYY cannot be submitted (validation catches any other format and does not allow submission)
2. Submit an exception successfully and check record in Exceptions listing to confirm date is correctly formatted (regression check)
…
> bug/WP-797: Exception expiration year allows too large a range of dates

- apcd_cms/src/apps/submissions/views.py
- apcd_cms/src/client/src/components/Admin/EditExceptionModal/EditExceptionModal.tsx
- apcd_cms/src/client/src/components/Admin/Extensions/AdminExtensions.tsx
- apcd_cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
- apcd_cms/src/client/src/components/Admin/ViewExceptionModal/ViewExceptionModal.tsx
- apcd_cms/src/client/src/components/Admin/ViewUsers/ViewUsers.tsx
- apcd_cms/src/client/src/components/Forms/Registrations/RegistrationForm.tsx
- apcd_cms/src/client/src/components/Registrations/RegistrationList/RegistrationList.tsx
- apcd_cms/src/client/src/components/Submissions/ViewFileSubmissions/ViewSubmissions.tsx
- apcd_cms/src/client/src/components/Submitter/Exceptions/ExceptionForm.tsx
- apcd_cms/src/client/src/components/Submitter/Exceptions/ExceptionFormPage.tsx
- apcd_cms/src/client/src/components/Submitter/Extensions/ExtensionFormInfo.tsx
1. Submitter submission is missing entity name
2. Exception edit modal should show approved expiration date label (matching with prod)
3. <Link> and navigate do not work with routes outside the app
[WP-816](https://tacc-main.atlassian.net/browse/WP-816)
[WP-815](https://tacc-main.atlassian.net/browse/WP-815)
[WP-817](https://tacc-main.atlassian.net/browse/WP-817)
1. Go to http://localhost:8000/submissions/list-submissions/ and see if entity name is populated
2. Go to http://localhost:8000/administration/list-exceptions/ - edit modal and see that the label - 'Approved Exception Date' is seen. This is not Requested Exception Date
3. On registration submission, the link navigation works
ticket navigation on failure rightly went to the page
> [APCD] Exception, Submission and navigation bugs

- apcd_cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html
- apcd_cms/src/apps/extension/views.py
Addresses bug where a user with multiple submitters will see duplicate applicable data period options on the extensions form
…
…
- Factors out the applicable data periods db query from collating the list of user's submitters, now keeps this list of data periods separate for each submitter
- Adds listener to business name dropdown to update list of applicable period options when business name (read: submitter) is changed
…
1. Go to http://localhost:8000/submissions/extension-request/
- If you only have one submitter available in the dropdown, Carrie can help add other submitters for you in our dev db
2. Check the 'Applicable Data Period' dropdown and confirm a sorted list of year-month entries are there, then select one and confirm the 'Current Expected Date' box populates with a date
3. …
> Bug: Duplicate applicable data periods in extensions form

- lccf_assets/header.css
<details><summary>For LCCF, fix vertical alignment of <code>.nav-links</code> in CMS menu.</summary>
This is a problem on all sites using `TACC_CORE_STYLES_VERSION = 2` but is most-noticeable on LCCF, because LCCF sets `.s-header.navbar { --nav-padding-vert: 10px; }` (and `.s-header .nav-link { top: unset; }` to partially resolve alignment.)
</details>
- fixes #325
- **fixes** `.s-header .nav-link` styles
<sup>(in a way that should be applied to Core-Styles instead)</sup>
1. Replace the content of LCCF's `header.css` with the new content.
2. Verify .nav-link` underline is at bottom of header.
3. Verify `.nav-link` text is vertically aligned center with search bar.
https://github.com/user-attachments/assets/6a525c8a-1436-4a55-84f4-9a3b7c57e56b
1. Add styles `/* To fix nav link alignment …
> fix(lccf): cms menu .nav-link alignment

- apcd_cms/src/apps/utils/apcd_database.py
- apcd_cms/src/apps/view_submitter_users/templates/view_submitter_users.html
- apcd_cms/src/apps/view_submitter_users/urls.py
- apcd_cms/src/apps/view_submitter_users/views.py
- apcd_cms/src/client/src/components/Submitter/ViewSubmitterUsers/EditRecordModal.tsx
- apcd_cms/src/client/src/components/Submitter/ViewSubmitterUsers/ViewRecordModal.tsx
- apcd_cms/src/client/src/components/Submitter/ViewSubmitterUsers/ViewSubmitterUsers.tsx
- apcd_cms/src/client/src/hooks/admin/index.ts
- apcd_cms/src/client/src/hooks/admin/useAdmin.ts
The Submitter Users Page shows records of all submitter users and allows admin to view and edit records accordingly.
- [WP-822](https://tacc-main.atlassian.net/browse/WP-822?isEligibleForUserSurvey=true)
I added necessary information including payor codes (shown as organization names), necessary filters, and added functionality to edit users' payor codes and notes.
1. Go to [the VIew Submitter Users page](http://localhost:8000/administration/view-submitter-users/).
2. Use the filters to sort users by status and payor codes.
3. Select a user and choose View Record under Actions to view that user's information.
4. Choose Edit Record under Actions for that user to edit that user's name, email, payor code, and notes.
> Task/WP-822: Improve Submitter Users Page

- lccf_assets/header.css
Rely on Core-Styles to fix CMS menu `.nav-link` alignment.
- fixes & simplifies #409
- requires https://github.com/TACC/Core-CMS/pull/905
- **deletes** code that Core-Styles now gives
- **deletes** obvious comments
1. Deploy/Replicate on https://pprd.lccf-portal.tacc.utexas.edu/.
2. View when navbar is expanded.
1. Verify `.nav-link` underline is at bottom of header.
2. Verify `.nav-link` text is vertically aligned center with search bar.
3. View when navbar is collapsed.
1. Verify `.nav-link`s are not too close to each other.
| LCCF Custom `header.css` | Core-Styles `…header.css` |
| - | - |
| <img width="960" alt="lccf custom header css content" src="https://github.com/user-attachments/assets/12c87860-5bce-4b86-a976-4bb285613901" /> | <img width="960" alt="core-styles header css …
> fix(lccf): align cms menu nav link via Core-Styles

- ecep_assets/css/site.css
- Footer is invisible (because…)
- Horizontal Rules are invisible (because…)
- All primary (i.e. neutral) colors are broken.
- fixes #412
- **changes** variable name in color calculation
1. Footer becomes visible.
| before | after |
| - | - |
| <img width="960" alt="before" src="https://github.com/user-attachments/assets/e28518d7-3b50-4ba0-ad36-c92ed79970f1" /> | <img width="960" alt="after" src="https://github.com/user-attachments/assets/bbc12582-a2cd-484c-a16c-4ab6176e721b" /> |
> fix: RT #32428 branding colors typo

- ecep_assets/html/snippets/js-news-open-external-articles-in-new-window.html
Allow an external news article to be shown on news page.
- **adds** a copy of the HTML from [ECEP website snippet #35](https://ecepalliance.org/admin/djangocms_snippet/snippet/35/change/)
1. Add article to [ECEP News](https://ecepalliance.org/news).
2. Tag the article `external`.
3. Add a hidden link at the end of the abstract:
```html
<p><a hidden="" href="https://ecepalliance.org/news/2023/11/01/2023-state-of-computer-science-education-report-released/">External link.</a></p>
```
4. Click the article on [ECEP News (published view)](https://ecepalliance.org/news/?preview).
5. **Verify it opens a different website in a new window.**
6. Click the article on [ECEP News (edit view)](https://ecepalliance.org/news/?edit).
7. **Verify it opens a different website in a new window.** …
> feat(ecep): RT-32428 list external news article

- apcd_cms/src/apps/utils/apcd_database.py
Very minor update to the query that pulls applicable data periods from the submitter calendar, as described in a call with UTH where business logic was explained. See ticket referenced below for more detailed information. 
- [WP-854](https://tacc-main.atlassian.net/browse/WP-854)
Query is updated so that it is selecting records where there is a submission id (no longer null as before), as well as cancelled = FALSE and granted_reprieve = FALSE
> WP-854 Updating Applicable Period Fetch Business Logic

- apcd_cms/src/apps/admin_extension/templates/list_admin_extension.html
- apcd_cms/src/apps/admin_extension/templates/view_admin_extension_modal.html
- apcd_cms/src/apps/admin_extension/views.py
- apcd_cms/src/client/src/components/Extensions/EditExtensionModal/EditExtensionModal.tsx
- apcd_cms/src/client/src/components/Extensions/ViewExtensionModal/ViewExtensionModal.tsx
Addresses testing bugs for the admin extension table
- [WP-859](https://tacc-main.atlassian.net/browse/WP-859)
- [WP-860](https://tacc-main.atlassian.net/browse/WP-860)
- [WP-861](https://tacc-main.atlassian.net/browse/WP-861)
- Removes extra layers of styles effecting the size of the extension modal
- Uses state to manage fields and listing in edit modal
- Updated extension modal so that it follows the style and layout of the Exception View/Edit modals
- Sorts extension listing by created by date rather than approved expiration date
1. Make sure to collect static since some static style sheets were changed. 
2. Go to [http://localhost:8000/administration/list-extensions/](http://localhost:8000/administration/list-extensions/) 
3. Check that listing is sorted by created by date from …
> task/WP-859-860-861 Admin Extension Listing

- apcd_cms/src/apps/utils/apcd_database.py
View Submitter Users table had multiple duplicate records, fixed query so that it no longer joins on submissions table. 
- [WP-885](https://tacc-main.atlassian.net/browse/WP-885)
removed join to submissions table
1. navigate to administration/view-submitter-users/ and verify table does not have multiple duplicate rows for each user
> WP-885 Duplicate Users in View Submitter Users table

- apcd_cms/src/apps/base/base.py
- apcd_cms/src/apps/registrations/views.py
A authenticated user with no groups should be able to submit registration request.
- [WP-882](https://tacc-main.atlassian.net/browse/WP-882)
1. Remove groups check
2. Add authenticated check
1. Remove all user groups for your user
2. Go to register/request to submit and submit.
3. Go to db and run query: `select * from registrations order by created_at desc LIMIT 1;`  to see your registration
> Bugs/WP-882: Registration for user with no apcd groups

- apcd_cms/src/apps/common_api/views.py
- apcd_cms/src/apps/utils/apcd_database.py
- apcd_cms/src/client/src/components/Submitter/Extensions/ExtensionsForm.tsx
Extension applicable data periods is using different where clause from extension expected dates resulting in periods with null expected dates.
- [WP-887](https://tacc-main.atlassian.net/browse/WP-887)
1. Use same where in database queries for both applicable data periods and extension expected dates.
2. the api for data periods is forcing apcd admin, where as it should also allow submitter admin. Adjusted that.
3. For submitter admin, we should check whether the user has access to the submitter.
…
1. As APCD_ADMIN, go to http://localhost:8000/submissions/extension-request/ and check all the applicable data periods
2. As SUBMITTER_ADMIN, go to http://localhost:8000/submissions/extension-request/ and check all the applicable data periods.
3. As SUBMITTER_ADMIN, open a new tab in browser and …
> WP-887: Fix for data periods and expected dates

- wtcs_assets/scripts/add-shopping-cart-icon.js
- wtcs_assets/snippets/add-shopping-cart-icon.html
- Clean up shopping cart icon script.
- Save snippet used to execute script.
- improves #448
- **refactored** script to add icon
- **added** new snippet
1. Open https://weteachcs.org/.
2. Verify icon renders at size of Portal login icon.
3. Verify link opens Registration in new window.
https://github.com/user-attachments/assets/87c31cf6-ab08-43f6-b63f-c8e7eba3c63c
I thought about dynamic image path, so icon can be served from same CDN parent path that loads the script, which would allow icon to be updated without updating script, but it opened up security holes I'd need to close and test. Easier to just update as necessary which is probably never.
> chore(wtcs): add icon - handle error, clear variables, save snippet

- a2cps_cms/Dockerfile
- apcd_cms/Dockerfile
- example_cms/Dockerfile
Update `…_cms` projects to use Core-CMS v4.26.0.
- similar to #451
- **changed** `Dockerfile`'s CMS image
1. Update https://github.com/TACC/Core-Portal-Deployments.
2. Deploy.
Buried and piecemeal within [internal testing doc](https://tacc-main.atlassian.net/wiki/x/5oAmJQ).
Goal is to avoid migration issues that will arise from a deploy of Core-CMS image from Core-CMS branches **after** https://github.com/TACC/Core-CMS/pull/908, but **before** https://github.com/TACC/Core-CMS/pull/927, https://github.com/TACC/Core-CMS/pull/928, https://github.com/TACC/Core-CMS/pull/929. Such migration issues occurred on APCD.
> deps(a2cps, apcd, example): cms v4.26.0

- apcd_cms/Dockerfile
Bump Core-CMS (for parity with A2CPS). No effect.
- **Irrelevant**: Fixes UI bugs in header that only affect `TACC_CORE_STYLES_VERSION = 0` sites.
- **Unused**: Adds CMS update to System Monitor plugin (used on very few CMS's).
> deps(apcd): cms v4.26.1

- apcd_cms/Dockerfile
Updates prod CMS to keep everything the same as v1.0.19 (prod CMS) with no react client but points base image to CoreCMS v4.26.1
…
1. Make build / make start
2. Ensure it looks like https://txapcd.org/ 
…
> task/Points v1.0.19 (prod cms tag) to TACC CMS image v4.26.1

- apcd_cms/src/apps/admin_extension/views.py
Remove Status 'None' from Edit Extensions modal
…
[WP-810](https://tacc-main.atlassian.net/browse/WP-810)
Remove Status 'None' from Edit Extensions modal
1. Open Edit Record modal from Extensions list
2. Make sure Status drop-down has no 'None' option.
…
> Remove Status 'None' from Edit Extension modal.

- apcd_cms/src/client/src/components/Registrations/ViewRegistrationModal/ViewRegistrationModal.module.css
View Registration Modal: h5 and h6 headers are not formatted <del>right</del> <ins>as they were on production as of 2025-03</ins>.
[WP-900](https://tacc-main.atlassian.net/browse/WP-900)
Add h5 and h6 CSS styling
1. Open View Registration modal, make sure the <del>right</del> <ins>production 2025-03</ins> CSS styling is applied to h5 and h6 tags
> Add h5 and h6 CSS styling.

- ecep_assets/site.css
Consolidate global styles into one stylesheet via `@import` (so less global snippets are used on CMS). Also, fix nav link hover underline being orange instead of gray.
0. Delete these snippets:
- `css-djangocms-picture-bug-fix`
- `css-fix-logo`
- `css-fix-neutral-colors`
- `css-links`
2. Image with captions (e.g. [this news article](https://pprd.ecep.tacc.utexas.edu/news/2024/08/22/ecep-as-a-central-hub-for-broadening-participation-in-computing-bpc-initiatives/)):
- has small text as caption
- is only as wide as article text area width
3. Homepage logo does not overflow header:
- when CMS nav menu is visible by default (wide screen)
- when CMS nav menu is collapsed (narrow screen)
- when CMS nav menu is collapsed (narrow screen)
4. Links in body text:
- are underlined by default
- have …
> refactor(ecep): fix nav link border color, consolidate global styles

- apcd_cms/src/apps/admin_extension/views.py
Fixed issue where admin extensions page created null datetime value that was wrong type.
> Hotfix: Null created_at value

- .github/workflows/apcd-cms.yml
Github workflow to auto-update `develop-apcd `when changes are pushed to main
- [WP-951](https://tacc-main.atlassian.net/browse/WP-951)
- Adds permissions: write-all to yaml
- Adds `sync` job to fetch latest main, checkout develop-apcd, and pull and merge main into develop-apcd [using this as a reference 
](https://stackoverflow.com/questions/76509304/running-github-action-to-keep-a-branch-up-to-date-with-main)
1. Need to check that the branch protections and [rulesets here](https://github.com/TACC/Core-CMS-Custom/rules/5328423?ref=refs%2Fheads%2Fdevelop-apcd) don't prohibit this action. Current rules throw this error when trying to merge main into develop-apcd
```
remote: error: GH013: Repository rule violations found for refs/heads/develop-apcd.
remote: Review all repository rules at …
```
> task/WP-951 Adds workflow to update develop-apcd to main

- .github/workflows/apcd-cms.yml
This reverts commit 033f72dccfbe1bdeb253691591616d8eac524a33 - workflow to update develop-apcd to main (#486)
- [WP-951](https://tacc-main.atlassian.net/browse/WP-951)
…
1.
…
> task/WP-951 Revert workflow to update develop-apcd to main (#486)

- tapisproject_assets/snippets/css-patch-missing-tapis-styles.html
https://tapis-project.org/ not loading Tapis-specific styles, because the setting that would trigger that is not loaded into container.
<details><summary>Background</summary>
Occurs on [attempt to deploy new version without being able to test on staging site](https://github.com/TACC/Core-Portal-Deployments/commit/08c8828a).
</details>
- https://github.com/TACC/Core-Portal-Deployments/commit/08c8828a
- similar to https://github.com/TACC/Core-CMS-Custom/pull/499
- **adds** snippet that loads missing styles
1. Open https://tapis-project.org/training/.
2. See thin table border with brighter link color.
3. Other tests may be available but are not recorded.
| before | after |
| - | - |
| <img width="960" height="465" alt="before" src="https://github.com/user-attachments/assets/6a1b9859-ed2c-441d …
> fix: (bandaid) tapis styles not loading

- wtcs_assets/snippets/css-color-scheme.html
Fix WeTeach_CS section headers wrong color since CMS update/deploy today.
- fixes clash with
- https://github.com/TACC/Core-Styles/pull/492
- https://github.com/TACC/Core-Styles/pull/495
- deployed via
- [this config](https://github.com/TACC/Core-Portal-Deployments/commit/2f732ca)
- [this action](https://jenkins.portals.tacc.utexas.edu/job/Core_Portal_Deploy/2290)
- **fixed** WeTeach_CS color scheme **with bandaids**
- **documented** color scheme **flaws**
1. Compare:
| before | after | note |
| - | - | - |
| [Home (Archive)](https://web.archive.org/web/20250327141019/https://weteachcs.org/) | [Home (Production)](https://weteachcs.org/) |
| [Courses (Archive)](https://web.archive.org/web/20250327141019/https://weteachcs.org/training-events/courses/) | [Courses …
> fix(wtcs): heading colors wrong

- cfde-cms/html/css-global-ad-hoc.html
- generic_assets/css/core-styles-fixes.css
Add common Core-Styles bug fixes.
None
- adds CFDE global ad-hoc styles snippet
- adds generic core-styles fixes stylesheet
1. Open https://pprd.netsage.tacc.utexas.edu/.
<sup>(Will later be https://pprd.cfde-cms.tacc.utexas.edu/.)</sup>
2. Verify space after a `<ul>` matches that after a `<p>`.
Tested on https://pprd.netsage.tacc.utexas.edu/ [^1] via [snippet #4](https://pprd.netsage.tacc.utexas.edu/admin/djangocms_snippet/snippet/4/change/).
[^1]: Will become https://cfde-cms.netsage.tacc.utexas.edu/.
> fix(generic,cfde): core-styles bugs
