TACC/Core-CMS-Custom

apcd-cms/Makefile
When testing Makefile commands, they did not work. These changes were effective.
=> fix(apcd-cms): Makefile copypasta (portal & cms)

apcd-cms/src/apps/admin_regis_table/views.py
Added database call for registrations via submission form app
…
…
…
1. Cannot be tested locally, as db call returns NoneType locally.
…
=> Database called; need to deploy to pprd to test

.github/workflows/demdata-cms.yml
This will create the workflow file for democratizing data and push up the containers for CMS commits. Basically a clone from the APCD one.
- https://github.com/TACC/Core-CMS-Custom/pull/39
Init Commit.
1. Run the workflow.
N/A
=> Create demdata Github Action

apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
New description for registration table.
- [discussion with Design](https://tacc-team.slack.com/archives/CQUA4D5KJ/p1669667188616439)
- changed text of template
I cheated—on just this one—by editing live markup.
I would have just done this via the CMS, if I could.[^1]
[^1]: Ideally, this text is in the CMS, not the template. I'll fix, or create a ticket to fix this, one day.
=> fix(apcd-cms): improve reg. list table desc

apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/css/table.css, apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
Added filtering based on registration status to registrations listing table
…
- [FP-1942](https://jira.tacc.utexas.edu/browse/FP-1942)
…
- Added filter HTML to listing template
- Added JS function for filtering the table
- Added CSS to table CSS for filter styling and placement
…
1. In `src/apps/admin_regis_table/views.py`, replace lines 21-23 with the following snippet:
(
True,                               #file_pv
True, …
=> task/FP-1942: Registrations listing table filter

apcd-cms/docker-compose.dev.yml
- https://github.com/TACC/Core-CMS/pull/579
=> feat(apcd-cms): fp-1952 isolate ES network

apcd-cms/src/apps/submissions/static/submissions/css/modal.css, apcd-cms/src/apps/submissions/templates/list_submissions.html, apcd-cms/src/apps/submissions/templates/view_submission_logs_modal.html, apcd-cms/src/apps/submissions/views.py
Refactor based off the previously merged in [task/FP-1855 Submissions List Page](https://github.com/TACC/Core-CMS-Custom/pull/63) PR
[FP-1885 - My (Completed) Submissions page](https://jira.tacc.utexas.edu/browse/FP-1885)
1. Removed `Created` column from table and added `Received` column
2. Adjusted `File Name` column sizing
3. Adjusted static text on the page
4. Adjusted modal layout to display label and value on the same line
1. In order to mock some data for local testing make the following changes in `apcd_cms/src/apps/submissions/views.py`:
<details>
<summary>View Snippet</summary>
Add the following to the top of the file:
`import datetime`
Replace line 38 with the following:
```js
submission_content = [
(
1,                                                      # submission_id
1, …
```
=> task/FP-1855 Completed Submissions Page Refactor

apcd-cms/src/apps/view_users/templates/view_users.html
=> Clearing out debuging statements.

apcd-cms/src/apps/admin_regis_table/templates/create_submitter_error.html, apcd-cms/src/apps/admin_regis_table/templates/create_submitter_success.html, apcd-cms/src/apps/admin_regis_table/templates/edit_registration_error.html, apcd-cms/src/apps/admin_regis_table/templates/edit_registration_success.html, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
Fixed add/drop contact buttons for registration form + patched back buttons redirecting to incomplete URL on action success/error
…
…
- Added missing `</script>` tag for JS script which handles adding/remove contact entries on reg form
- Changed comment format for HTML comments in same script template as above
- Added trailing `/` to URLs connected to buttons which redirect back to listing page after action success/error
…
1. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
(
122023, …
=> fix: Add/Drop Contact button + action success/error redirect

apcd-cms/src/apps/admin_regis_table/views.py, apcd-cms/src/apps/utils/apcd_database.py
…
…
- Logging statements in the table's view class and `get_registrations()` SQL function
…
1. No testing needed!
…
=> Registrations listing: added some logging statements to debug listing table

apcd-cms/src/apps/admin_submissions/templates/view_admin_submission_logs_modal.html, apcd-cms/src/apps/admin_submissions/views.py, apcd-cms/src/apps/submissions/templates/list_submissions.html, apcd-cms/src/apps/submissions/templates/view_submission_logs_modal.html, apcd-cms/src/apps/submissions/views.py, apcd-cms/src/apps/utils/apcd_database.py
Reverts TACC/Core-CMS-Custom#102
=> Revert "hotfix/view-submission-fixes"

apcd-cms/src/apps/exception/templates/exception_submission_form/exception_other_form.html, apcd-cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html, apcd-cms/src/apps/extension/templates/extension_submission_form/extension_submission_form.html, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html, apcd-cms/src/apps/utils/apcd_database.py
Proper emails in forms were not submitting because of a pattern check not allowing capital letters
[FP-1980 [APCD] Front-end email audit doesn't allow capital letters](https://jira.tacc.utexas.edu/browse/FP-1980)
Added A-Z to email pattern check in submission forms for:
- exceptions
- extensions
- edit registrations
- registrations
1. Open [http://localhost:8000/request/request-to-submit/](http://localhost:8000/request/request-to-submit)
2. Make sure you can submit a form with an email that has a capital letter. You may see an error after submitting the form that's ok. Just make sure the field doesn't block you from submitting
3. Open [http://localhost:8000/administration/list-registration-requests/](http://localhost:8000/administration/list-registration-requests/)
4. Make sure you can …
=> bug/FP-1980 Fix pattern for email input to allow capital letters

apcd-cms/src/apps/utils/apcd_database.py
Fixing the lowercase function from JS to Python
1. http://localhost:8000/register/request-to-submit/
2. Submit form
=> Changing lowercase function to pythonic

apcd-cms/src/apps/admin_regis_table/views.py
Fix for list bug that causes create submitter action to fail on every attempt
…
…
- Added `[0]` index on line in POST which grabs single registration record based on registration id, to correctly index over record's tuple
…
1. Nothing to test locally.
…
=> fix: Create submitter form writing bug

apcd-cms/src/apps/submissions/views.py, apcd-cms/src/apps/utils/apcd_database.py
Implemented data loading improvements for user submissions page that were previously made for the admin submissions page in  #129 
- [FP-1979](https://jira.tacc.utexas.edu/browse/FP-1979)
- Changed the query to get the list of submissions by a user. The query now returns a pre-built JSON object with all the logs. As a result we only have to make one db query to get the entire dataset. Making changes to the data is also improved since we can reference fields by their names instead of indexes.
1. In order to mock some data for local testing make changes to the following files
`apcd_cms/src/apps/submissions/views.py:`
<details>
<summary>View Snippet</summary>
Replace line 29 with the following:
```js
submission_content = [
{
'submission_id': None,
'submitter_id': None,
'file_name': None, …
```
=> task/FP-1979 User Submissions Pagination Improvements

apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/css/table.css, apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html, apcd-cms/src/apps/admin_regis_table/templates/view_registration_modal.html, apcd-cms/src/apps/admin_regis_table/views.py, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html, apcd-cms/src/apps/registrations/templates/submission_form/submission_success.html, apcd-cms/src/apps/registrations/views.py, apcd-cms/src/apps/utils/apcd_database.py
Registration form updates based on feedback from UTH from 4/26 meeting
…
- [WP-89](https://jira.tacc.utexas.edu/browse/WP-89)
…
- Org type dropdown now writes org code to database rather than org display name (e.g. `tpa_aso` vs "Plan Administrator"
- File types to be submitted are now stored per-entity rather than per-registration (and cascading updates to util functions, view, and list registrations table)
- Removed file submission method (SFTP, HTTPS, etc) from form and relevant data utils/view functions
- Removed field length and pattern restrictions from NAIC and License codes for registered entities, now fields accept any-length digit
- On successful form submission, success page now displays registration id for that registration for user reference
…
***We will need to test that, …
=> task/WP-89: Registration form UTH feedback

apcd-cms/src/apps/admin_regis_table/static/admin_regis_table/css/table.css, apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html, apcd-cms/src/apps/admin_regis_table/urls.py, apcd-cms/src/apps/admin_regis_table/views.py
Adds business name filter and pre-sort by date for list registration requests page
…
- [WP-90](https://jira.tacc.utexas.edu/browse/WP-90)
…
- Pre-sort registrations data in view, ordering entries from newest to oldest received
- Added business name filter to page, options for said filter in view, and a new style for said filter's size
- Added url patterns to accommodate multiple query options on this page (status + business name)
…
1. Replace lines 70-72 in `apps/admin_regis_table/views.py` with the following:
(
'2013-01-23 10:49:36.880753',          #posted_date
122023, …
=> task/WP-90 List registrations UTH feedback

README.md, apcd-cms/README.md, demdata_cms/README.md, docs/develop-project.md, docs/run-project.md, example_cms/README.md, matcssi_cms/README.md
Documentation specific to projects (new and old).
- follow-up to #172
- follow-up to #173
- **changed** each project's `README` (just polish)
- **added** `docs/develop-project.md`
- **changed** main `README` to reference new `docs/develop-project.md`
N/A
=> docs: project readme polish

apcd-cms/src/apps/utils/apcd_database.py, apcd-cms/src/apps/view_users/static/view_users_table/css/modal.css, apcd-cms/src/apps/view_users/templates/view_user_edit_error.html, apcd-cms/src/apps/view_users/templates/view_user_edit_modal.html, apcd-cms/src/apps/view_users/templates/view_user_edit_success.html, apcd-cms/src/apps/view_users/templates/view_user_modal.html, apcd-cms/src/apps/view_users/templates/view_users.html, apcd-cms/src/apps/view_users/views.py
Added Edit Modal which updates User's Name, Email, Status, Role and Notes
…
…
Added edit, success, and error templates. edited table to show dropdown choice. Added Edit User function query
…
1. Tested using test db
=> Edit data/jira wp 12 user listing editdata

README.md, apcd-cms/README.md, demdata_cms/README.md, example_cms/README.md, matcssi_cms/README.md, tapisproject_cms/README.md
**README's**: Fix typo. Improve accuracy. Use relative links.
None.
<sup>I found this stuff while testing.</sup>
N/A-ish. Skipped.
=> docs(README): clarify settings_local dir & "0 static assets"

apcd-cms/src/taccsite_cms/settings_custom.py
Merge #197 code into a new release branch.
Thus an upcoming PR that recreates #195 for prod can use this target branch too.
=> hotfix: SESSION_COOKIE_SECURE = True (#197)

apcd-cms/src/apps/submissions/urls.py, apcd-cms/src/apps/submissions/views.py, apcd-cms/src/taccsite_cms/custom_app_settings.py, apcd-cms/src/taccsite_cms/urls_custom.py
=> hotfix: Check submitter endpoint - restore imports on unused code

apcd-cms/src/apps/submissions/views.py
=> hotfix: Restore commented out imports

matcssi_cms/Dockerfile
Update MatCSSI to v3.12.0-beta.3 Core-CMS.
None.
- **changed** Dockerfile
1. Verify `site.css` on pre-prod matches prod.
2. Verify styles on pre-prod matches prod.
Mostly skipped. _Pages had identical styles, but different content, which would be a confusing record._
- [Staging has updated version, now.](https://github.com/TACC/Core-CMS-Custom/assets/62723358/d2a6d6d3-03e3-4d57-8910-1b11f371e495)
- [Production has updated version, now](https://github.com/TACC/Core-CMS-Custom/assets/62723358/8f999bed-e458-4cb5-be3e-edc3b003f816)
=> feat(matcssi): v3.12.0-beta.3

apcd-cms/src/apps/registrations/urls.py
Disables the `/register/request-to-submit/` path.
=> disable old reg form

.github/workflows/apcd-cms.yml
- Updates workflows
- Updates short sha var with 7-characters to match github
- Creates new branch name var to tag images with branch/tag name in addition to short sha
=> Update apcd workflow

apcd-cms/src/apps/utils/registrations_data_formatting.py
Checks for empty values on registration contacts table
…
…
- Checks if columns are defined for contacts table, otherwise defaults them to None
…
1. In apps/admin_regis_table/views.py, replace lines 71-73 in `apps/admin_regis_table/views.py` with the following:
(
'2013-01-23 10:49:36.880753',          #posted_date
True,                               #submitting_for_self
'received',                           #registration_status
'carrier',                #org_type
'BRule Insurance Company',    #business_name
'7440 Woodland Drive',              #mail_address …
=> Check for missing values on contacts table

docs/upgrade-project.md
=> fix(docs): upgrade, move images, copy-pasta desc

apcd-cms/src/apps/registrations/templates/submission_form/registration_form_body.html, apcd-cms/src/apps/registrations/templates/submission_form/registration_form_scripts.html
Updates to registration form from UTH's beta testing on QA site.
…
- [WP-481](https://jira.tacc.utexas.edu/browse/WP-481)
- [WP-478](https://jira.tacc.utexas.edu/browse/WP-478)
…
- Under the 'Registration Year' field, added help text to show that only years including and later than 2023 are valid.
- Under the 'Claims and Encounters Volume' field in Entities, added helper text to specify inputs must be whole numbers.
- The 'Role' field under the Contacts section now reads 'Company Role'
…
1. Go to https://localhost:8000/register/request-to-submit
2. Confirm the above 'Changes' appear in the corresponding places
3. Repeat for the following:
- http://localhost:8000/administration/list-registration-requests/ -> Edit Record on any row
- …
=> task/WP-481: Registration form updates

apcd_cms/src/apps/utils/registrations_data_formatting.py
Quick hotfix to fix issue with registration status being empty.
…
…
1. Go to List Registration Requests page and verify it is loading properly. 
…
=> Hotfix: Empty Registration Status

ecep_cms/Dockerfile
Fix conditional Elasticsearch.
- [CMD-176](https://tacc-main.atlassian.net/browse/CMD-176)
- https://github.com/TACC/Core-CMS/pull/857
- **changed** Core-CMS image
1. Verify pages can still be published.
2. Verify search still works.
Skipped.
=> feat(ecep): CMD-176 conditional elastic search

apcd_cms/src/apps/exception/static/forms/css/exception_submission_form.css, apcd_cms/src/apps/exception/templates/exception_submission_form/exception_threshold_form.html, apcd_cms/src/apps/utils/apcd_database.py
Merge PR
[WP-689](https://tacc-main.atlassian.net/browse/WP-689)
Original PR: https://github.com/TACC/Core-CMS-Custom/pull/306
Did a quick test
=> Merge hotfix wp-689 to main

.github/CODEOWNERS
Add me as codeowner on git config, assets, demdata, and docs.
I want to be pinged for PRs on certain files.
Another contributor can use this file to request the same.
=> enhance: CODEWOWNERS

apcd-cms/src/apps/admin_submissions/templates/list_admin_submissions.html, apcd-cms/src/client/src/components/Admin/Submissions/AdminSubmissions.module.css, apcd-cms/src/client/src/components/Admin/Submissions/AdminSubmissions.tsx
Add pagination to Admin Submissions component
[WP-703](https://tacc-main.atlassian.net/browse/WP-703)
1. git checkout task/submissions-pagination
2. open two terminals - one for client and one for main. 
3. cd apcd-cms/src/client and npm ci, then npm run build and then npm run dev
4. in another terminal, cd apcd-cms and make build and then make start.
5. Edit code to set the limit to 3 (for testing pagination): https://github.com/TACC/Core-CMS-Custom/blob/task/submissions-pagination/apcd-cms/src/apps/admin_submissions/views.py#L55
6. Go to page and check pagination http://localhost:8000/administration/list-submissions/
=> Task/WP-703: Add react pagination to admin submissions

wtcs_assets/snippets/color-scheme.html, wtcs_assets/snippets/css-homepage-banner-desktop.html, wtcs_assets/snippets/google-map.html, wtcs_assets/snippets/homepage-banner-mobile.html
Save snippets for [WeTeach_CS](https://prod.wtcs.tacc.utexas.edu/) website.
- saved as I finished wide screen homepage banner before giving back to designer
- saved the day before scheduled launch
- **added** snippets
N/A
Skipped.
=> feat(wtcs): snippets

apcd-cms/src/apps/admin_extension/views.py, apcd-cms/src/apps/utils/apcd_database.py, apcd-cms/src/client/src/components/Extensions/EditExtensionModal/EditExtensionModal.tsx, apcd-cms/src/client/src/utils/dateUtil.ts
1. Use the applicable expected list of applicable values. With drop down, remove the chance of bad values from user.
2. Map the value to the available value - use date conversion from label to api value
[WP-768](https://tacc-main.atlassian.net/browse/WP-768)
1. Use edit modal and adjust dates: http://localhost:8000/administration/list-extensions/
=> [APCD] Extension Form Edit Modal -  Expected Date error 

apcd-cms/src/apps/admin_extension/views.py, apcd-cms/src/client/src/components/Admin/Extensions/AdminExtensions.tsx
Pending is now default for status. Also fixed the "Clear Options" button so it is consistent with other pages. 
…
1.
…
=> Pending for default status

apcd_cms/src/apps/submissions/static/submissions/css/table.css, apcd_cms/src/apps/submissions/views.py, apcd_cms/src/apps/utils/apcd_database.py, apcd_cms/src/client/src/components/Extensions/EditExtensionModal/EditExtensionModal.tsx, apcd_cms/src/client/src/components/Submissions/ViewFileSubmissions/ViewSubmissions.tsx, apcd_cms/src/client/src/components/Submitter/Extensions/ExtensionFormInfo.tsx, apcd_cms/src/client/src/components/Submitter/Extensions/ExtensionsForm.tsx, apcd_cms/src/client/src/hooks/submissions/index.ts, apcd_cms/src/client/src/hooks/submissions/useSubmissions.ts
Request was to filter table by Payor Code. For this a new payor code column was added
Added a column for Payor Code and created a dropdown for dynamically populated options
1. make sure both filters are populated along with the sort by date.
2. test filters and sort in different combinations.
3. compare results of tests on table
how page looks to start
How page looks after filter applied
=> Feature/apcd react conversion/task/jira wp434 add payor code filter

ptdatax_assets/open-certain-links-in-new-tab.js
Open certain pages in new tab, even though they are internal.
- [CMD-193](https://tacc-main.atlassian.net/browse/CMD-193)
- requires https://github.com/TACC/Core-CMS/pull/902
- **added** a script
See https://github.com/TACC/Core-CMS/pull/902.
=> feat(ptdatax): cmd-193 new tab links

ptdatax_assets/snippets/open-certain-links-in-new-tab.html
Save script as a snippet instead (so `/static/…` paths would work).
- refactors #389
- same as #389
=> refactor(ptdatax): CMD-193 new tab links

apcd_cms/src/apps/admin_regis_table/views.py, apcd_cms/src/apps/utils/apcd_database.py, apcd_cms/src/apps/view_users/views.py, apcd_cms/src/client/src/components/Forms/Registrations/RegistrationForm.tsx, apcd_cms/src/client/src/components/Registrations/EditRegistrationModal/EditRegistrationModal.tsx, apcd_cms/src/client/src/components/Registrations/RegistrationList/RegistrationList.tsx, apcd_cms/src/client/src/hooks/registrations/index.ts, apcd_cms/src/client/src/hooks/registrations/useForm.ts
Merging the below features from main to feature branch. Biggest feature is registration edit with status.
* Allow 0 in registration forms: total_covered_lives, claims_encounters_volume, total_claims_value ( #[319](https://github.com/TACC/Core-CMS-Custom/pull/319))
* When None organization filter is selected on Admin View Users page, make sure None stays selected on load of the filter (#[317](https://github.com/TACC/Core-CMS-Custom/pull/317))
* Add 'Withdrawn' to status options #[314](https://github.com/TACC/Core-CMS-Custom/pull/314)
* Add status change to edit registration modal #[312](https://github.com/TACC/Core-CMS-Custom/pull/312)
[WP-811](https://tacc-main.atlassian.net/browse/WP-811)
1. Registration Form edit modal
2. New registration
3. View Users
=> Merge features from main to apcd feature branch

apcd_cms/src/client/src/components/Admin/ViewUsers/ViewUsers.tsx
…
- [WP-801](https://tacc-main.atlassian.net/browse/WP-801)
…
- Changed 'View Users' to 'List Users' to match nav bar title
- Updated page description to be more descriptive
…
1. Go to http://localhost:8000/administration/view-users/ and confirm above changes.
…
=> task/WP-801: Update text on admin users listing

apcd_cms/src/apps/utils/apcd_database.py
1. Merge [PR](https://github.com/TACC/Core-CMS-Custom/pull/306) db changes to feature branch
[WP-821](https://tacc-main.atlassian.net/browse/WP-821)
1. Submit threshold exception. Below is a new exception
```
required_threshold | exception_id
--------------------+--------------
100 |         1077
```
=> WP-821[APCD] Writing the required threshold to DB

README.md
Distinguish custom CMS vs custom assets.
None
- **changed** document
https://github.com/TACC/Core-CMS-Custom/blob/docs/cms-vs-assets/README.md
=> docs: custom_project_dir → customproject_cms vs. _assets

README.md, README_assets.md, README_cms.md
Polish the root-level `README`s.
=> docs(README): reorganize/optimize content

ctrn_assets/snippets/iframe-graph-participation-static-clone.html, ctrn_assets/snippets/iframe-graph-participation.html, ctrn_assets/snippets/iframe-graph-regions-static-clone.html, ctrn_assets/snippets/iframe-graph-regions.html, ctrn_assets/snippets/iframe-graph-trauma.html
Save all CTRN graph snippets in current state.
=> chore(ctrn): save iframes as of today

lccf_assets/snippets/css-core-styles-fixes.html, lccf_assets/snippets/css-header-and-logo.html, lccf_assets/snippets/html-warning-about-cms-version.html
Save bandaid to fix header overflow. Save other snippets.
N/A. Just saving snippets.
=> chore(lccf): save bandaid fix for logo overflowing header

README.md
=> docs(README): better clarify "two ways to use"

README_assets.md, README_cms.md
Test merge options on PR to a `develop` branch.
=> test: add new line to a readmes

README.md, README_assets.md, README_cms.md
Test whether auto-delete happens on PR to `main` branch which is protected by "Main Branch" ruleset.
=> test: add line to readme

ctrn_assets/cms.css, ctrn_assets/snippets/css-every-page-except-home.html, ctrn_assets/snippets/css-global.html, ctrn_assets/snippets/css-news-page.html
Move inline styles to global styles for every page except home page.
> [!IMPORTANT]
> Requires every page have snippet "CSS: Every Page Except Home".
=> feat(ctrn): global styles instead of inline styles

ospo/README.md
=> fix(opso): README
